// SPDX-License-Identifier: GPL-3.0-or-later
import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // src/ipc/generated-types.ts is machine-generated by `cargo run -p
    // xtask -- export-bindings` (design-02 §4.3/D-17) - it is committed and
    // CI drift-checks it against the Rust source of truth, but it is never
    // hand-edited, so it is excluded from linting the same way `dist` is.
    ignores: ["dist", "src-tauri/target", "coverage", "src/ipc/generated-types.ts"],
  },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactHooks.configs.flat["recommended-latest"],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  {
    // Node-context config files (not shipped to the browser/webview).
    files: ["*.config.{js,ts}", "src/test/setup.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.node, ...globals.browser },
    },
  },
);
