// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAppInfo: () => __TAURI_INVOKE<AppInfoDto>("get_app_info"),
	getEngineInfo: () => typedError<EngineIdentity, PublicError>(__TAURI_INVOKE("get_engine_info")),
	getEngineCapabilities: () => typedError<EngineCapabilities, PublicError>(__TAURI_INVOKE("get_engine_capabilities")),
	selectInputFiles: () => typedError<string[], PublicError>(__TAURI_INVOKE("select_input_files")),
	selectInputDirectory: () => typedError<string | null, PublicError>(__TAURI_INVOKE("select_input_directory")),
	selectOutputDirectory: () => typedError<string | null, PublicError>(__TAURI_INVOKE("select_output_directory")),
	revealPath: (path: string) => typedError<null, PublicError>(__TAURI_INVOKE("reveal_path", { path })),
	openPath: (path: string) => typedError<null, PublicError>(__TAURI_INVOKE("open_path", { path })),
	inspectInputs: (paths: string[]) => typedError<InputInspectionDto[], PublicError>(__TAURI_INVOKE("inspect_inputs", { paths })),
	/**
	 *  "Add Folder" (architecture.md §13.2): scans `directory` for candidate
	 *  `.pgn` inputs and returns them already inspected, for review before
	 *  they are added to the source list.
	 */
	scanInputDirectory: (directory: string, options: ScanInputDirectoryOptions) => typedError<DirectoryScanDto, PublicError>(__TAURI_INVOKE("scan_input_directory", { directory, options })),
	validateJob: (spec: JobSpec) => typedError<ValidationReportDto, PublicError>(__TAURI_INVOKE("validate_job", { spec })),
	compileJobPreview: (spec: JobSpec) => typedError<CommandPreviewDto, PublicError>(__TAURI_INVOKE("compile_job_preview", { spec })),
	startJob: (spec: JobSpec) => typedError<JobAcceptedDto, PublicError>(__TAURI_INVOKE("start_job", { spec })),
	cancelJob: (jobId: string) => typedError<null, PublicError>(__TAURI_INVOKE("cancel_job", { jobId })),
	getJob: (jobId: string) => typedError<JobRecordDto, PublicError>(__TAURI_INVOKE("get_job", { jobId })),
	listRecentJobs: (limit: number) => typedError<JobSummaryDto[], PublicError>(__TAURI_INVOKE("list_recent_jobs", { limit })),
	deleteJobHistory: (jobId: string) => typedError<null, PublicError>(__TAURI_INVOKE("delete_job_history", { jobId })),
	/**
	 *  "Save Job" (architecture.md §13.7): exports a completed job's
	 *  reproducible manifest to a user-chosen file via the native save dialog.
	 *  `Ok(None)` means the user cancelled the dialog - not an error.
	 */
	exportJobManifest: (jobId: string) => typedError<string | null, PublicError>(__TAURI_INVOKE("export_job_manifest", { jobId })),
	getSettings: () => typedError<SettingsDto, PublicError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (patch: SettingsPatchDto_Deserialize) => typedError<SettingsDto, PublicError>(__TAURI_INVOKE("update_settings", { patch })),
};

/* Types */
/**  `get_app_info` response (design-02 §4.1: `{ appVersion, os, arch }`). */
export type AppInfoDto = {
	appVersion: string,
	os: string,
	arch: string,
};

/**
 *  The kind of a planned or published output file (design-02 §1.1).
 * 
 *  Shared between the engine layer (`TemporaryOutput`/`FinalOutput` in
 *  `engine::command_compiler`) and the domain's own [`OutputArtifact`], so it
 *  lives here rather than in `engine/` — matching the explicit placement in
 *  the Phase 1a task scope and architecture.md §7.1's "dependencies point
 *  inward" rule (the engine module may depend on this domain type; the
 *  domain must never depend on the engine module).
 */
export type ArtifactKind = "uniqueGames" | "duplicateGames" | "reportJson" | "reportText" | "logText";

/**
 *  What to do with games the engine cannot parse cleanly (architecture.md
 *  §5.1 item 14, §11.6; design-02 §0 finding 2, D-007 V-5, D-6).
 * 
 *  There is deliberately no "separate file" variant: empirically, a single
 *  `pgn-extract` invocation cannot route broken games to their own output —
 *  without `--keepbroken` they are dropped everywhere (including the
 *  non-matching file); with it they land in the *main* output. Making the
 *  impossible option unrepresentable (rather than accepting it and silently
 *  downgrading it) is the enforcement mechanism for architecture.md §29 here.
 */
export type BrokenOutput = 
/**  Default: broken games are dropped (no `--keepbroken`). */
"discard" | 
/**  `--keepbroken`: broken games land in the main output. */
"keepInMainOutput";

/**
 *  Text-transform cleanup options (architecture.md §9.2; design-02 §4.1
 *  `cleanup`).
 * 
 *  Design-02 delta: the architecture document's illustrative
 *  `CleanupOptions` (§9.2) also has `remove_all_tags: bool` (`--notags`/`-7`).
 *  Design-02 explicitly drops this from V1 (row 12, Decision D-13: "V1 emits
 *  no ... `-7`/`--notags`"); it is capability-map-only, never wired to a
 *  `JobSpec` field. This module follows design-02 and omits the field.
 */
export type CleanupOptions = {
	removeComments: boolean,
	removeVariations: boolean,
	removeNags: boolean,
	removeMoveNumbers: boolean,
	removeResults: boolean,
	/**
	 *  Named tags to drop via repeated `--detag <Tag>` (design-02 row 11).
	 *  Each entry must match `^[A-Za-z][A-Za-z0-9]*$`; the compiler rejects
	 *  anything else as `InvalidSpec` rather than emitting a token the
	 *  engine would misparse.
	 */
	removeTags: string[],
	rejectBadResults: boolean,
	fixResultTags: boolean,
};

/**
 *  `compile_job_preview` response (design-02 §4.1). A pure presentation
 *  shape for the Review screen - deliberately not
 *  `engine::command_compiler::CompiledEngineCommand` itself, which carries
 *  OS-native `OsString` argv and an `EngineExecutable` newtype that must
 *  never reach the frontend (design-02 §1.6's never-executed guarantee: no
 *  code outside the engine module should even be able to *name* the
 *  sidecar path).
 */
export type CommandPreviewDto = {
	displayCommand: string,
	argv: string[],
	criteriaFiles: CriteriaFilePreviewDto[],
	plannedArtifacts: PlannedArtifactDto[],
};

/**
 *  What to do when a planned output path already exists at publication time
 *  (architecture.md §11.5; design-02 §3.5). Phase 1a only *stores* this
 *  choice on the spec; acting on it (numeric-suffix search, recycle-bin
 *  replacement, no-replace atomic rename) is filesystem I/O and belongs to
 *  Phase 1b (design-02 §3.4 step 6).
 */
export type ConflictPolicy = "fail" | "addNumericSuffix" | "replaceAfterConfirmation";

export type CriteriaFilePreviewDto = {
	relativePath: string,
	content: string,
};

/**
 *  `scan_input_directory` response: the matched files, already run through
 *  the exact same [`inspect_inputs`] pipeline "Add Files" uses (so sizes,
 *  readability, and warnings are computed identically - never duplicated
 *  logic), plus enough truncation/scope metadata for the Files screen to
 *  show an honest "found N files..." review before anything is actually
 *  added (architecture.md §13.2).
 */
export type DirectoryScanDto = {
	files: InputInspectionDto[],
	/**
	 *  Echoes back what was actually used, so the UI can label the result
	 *  accurately ("12 files, including subfolders") without trusting its
	 *  own possibly-stale local state.
	 */
	recursive: boolean,
	directoriesScanned: number,
	truncated: boolean,
	truncationNotes: string[],
};

/**
 *  Whether a duplicate-games audit file, if the engine produces one as a
 *  side effect of `OperationPlan::duplicates`, should be published.
 * 
 *  See the field doc on [`OutputPlan::duplicate_games`] for how this
 *  interacts with `OperationPlan::duplicates`.
 */
export type DuplicateOutput = "none" | "audit";

/**
 *  How to treat games whose move sequence/hash repeats an earlier game in
 *  input order (architecture.md §10.7; design-02 §0 finding 1, D-007 V-1/V-2,
 *  D-1).
 * 
 *  `-d` and `-D` are mutually exclusive at the engine level (exit 1 if both
 *  are given); both `ReportAndKeepFirst` and `SuppressKeepFirst` *divert*
 *  duplicates out of the main output, keeping only the first-encountered
 *  copy — they never merely "additionally write" an audit file next to an
 *  unfiltered main output. The two variants produce byte-identical main
 *  outputs; the only difference is whether an audit file exists at all.
 */
export type DuplicatePolicy = 
/**  No duplicate handling: emit neither `-d` nor `-D`. */
"none" | 
/**
 *  `-d<path>` alone: divert later duplicate copies to an audit file,
 *  main output keeps only first copies.
 */
"reportAndKeepFirst" | 
/**
 *  `-D` alone: silently divert (discard) later duplicate copies, no
 *  audit file, no path argument.
 */
"suppressKeepFirst";

/**  ECO/opening classification (`-e<eco.pgn>`) toggle (design-02 §4.1). */
export type EcoOptions = {
	enabled: boolean,
};

/**
 *  What a specific pinned `pgn-extract` build can do (architecture.md §10.4;
 *  design-02 §1.7).
 * 
 *  `false` on any field is a hard capability gate: the compiler returns
 *  `CompileError::UnsupportedOption` rather than dropping, downgrading, or
 *  approximating the corresponding request (architecture.md §29). Help-text
 *  parsing is explicitly not the contract (architecture.md §10.4) — this
 *  struct is populated from a tested static map for the pinned build
 *  (`engine::capability`), cross-checked at startup against the running
 *  binary's identity (Phase 1b concern; not implemented here).
 */
export type EngineCapabilities = {
	identity: EngineIdentity,
	/**  `-D`/`-d` family works at all. */
	duplicateDetection: boolean,
	/**  `-d` specifically (diverts duplicates *and* writes an audit file). */
	duplicateAuditFile: boolean,
	/**  `-Z` disk-backed duplicate table. */
	externalDuplicateTable: boolean,
	/**  `-c<master.pgn>` check-file support. */
	checkFile: boolean,
	/**  `-e<eco.pgn>` ECO/opening classification. */
	ecoClassification: boolean,
	/**  `FENPattern`/`FENPatternI` criteria-file lines. */
	fenPatterns: boolean,
	/**  `-v<variations>` textual opening-line filters. */
	textualVariations: boolean,
	/**  `--fixresulttags`. */
	fixResultTags: boolean,
	/**  `--nobadresults`. */
	rejectBadResults: boolean,
	/**
	 *  Whether a *separate* broken-games output file is possible in one
	 *  pass. Always `false` for this engine family (architecture.md §5.1
	 *  item 14, §11.6; design-02 D-007 V-5) — kept as an explicit field
	 *  rather than removed so the capability map stays self-documenting
	 *  about a limitation callers might otherwise assume exists.
	 */
	separateBrokenOutput: boolean,
	/**
	 *  Output notations this build can produce. V1 ships `[San]` only
	 *  (design-02 D-13); requesting anything not in this list is
	 *  `CompileError::UnsupportedOption`.
	 */
	supportedOutputFormats: OutputNotation[],
	/**
	 *  Whether the sidecar can address non-ACP-representable (e.g.
	 *  non-Latin Unicode) paths, per the startup Unicode-path probe
	 *  (design-02 Decision D-3). Not consulted by the compiler itself
	 *  (`compile` never touches the filesystem); recorded here because it
	 *  is a capability of the pinned build like any other, and Phase 1b's
	 *  `validate_job` gates on it.
	 */
	unicodePaths: boolean,
};

/**  Identity of a verified `pgn-extract` sidecar build (design-02 §1.7). */
export type EngineIdentity = {
	/**  The engine's own `CURRENT_VERSION` string, e.g. `"v26-06"`. */
	version: string,
	/**  SHA-256 of the sidecar executable, lowercase hex. */
	sha256: string,
	/**
	 *  Rust target triple the sidecar was built for, e.g.
	 *  `"x86_64-pc-windows-msvc"`.
	 */
	targetTriple: string,
};

/**
 *  The closed error-code taxonomy (architecture.md §18.1; design-02 §5.1).
 * 
 *  This is the complete V1 set as enumerated in design-02 §5.1's
 *  "raised by" table, plus one Phase 3 addition. Real construction is
 *  intentionally NOT implemented here (see [`PublicError`]'s doc comment) —
 *  this Phase 1a module only needs the closed set to exist so [`JobResult`],
 *  [`PublicError`], and [`JobWarning`] can be typed completely rather than
 *  with a placeholder `String`.
 * 
 *  **`AnnotatedDuplicatesSuppressed` (Phase 3):** every later addition to
 *  this enum before Phase 3 (`crate::errors`'s `path_not_allowed`,
 *  `job_not_active`, `directory_not_readable_io`,
 *  `export_destination_collision`, `invalid_saved_manifest`) deliberately
 *  *reused* an existing variant rather than growing the enum, each with a
 *  doc comment explaining why the reused code was still an honest fit. This
 *  one variant breaks that pattern on purpose: architecture.md §24's Phase 3
 *  exit criterion and §27's risk table both name "annotated-duplicate
 *  warnings" as their own concern (a *content* advisory — "this audit file
 *  holds annotations you may want to look at" — not a procedural/technical
 *  failure), and none of the other 18 members describe anything like it.
 *  Reusing an unrelated one (say, `EngineOutputInvalid`, which normally means
 *  "this file does not look like valid PGN") would be more misleading than
 *  adding a correctly-named 19th member — the same honesty rule
 *  (`crate::errors`'s module doc: never blur what a code actually means)
 *  argues for a new variant here rather than against it.
 */
export type ErrorCode = "INPUT_NOT_FOUND" | "INPUT_NOT_READABLE" | "INPUT_OUTPUT_COLLISION" | "OUTPUT_NOT_WRITABLE" | "OUTPUT_EXISTS" | "INSUFFICIENT_DISK_SPACE" | "INVALID_JOB_SPEC" | "UNSUPPORTED_ENGINE_OPTION" | "ENGINE_MISSING" | "ENGINE_TAMPERED" | "ENGINE_START_FAILED" | "ENGINE_EXIT_NONZERO" | "ENGINE_OUTPUT_MISSING" | "ENGINE_OUTPUT_INVALID" | "JOB_ALREADY_RUNNING" | "JOB_CANCELLED" | "TEMP_CLEANUP_FAILED" | "HISTORY_WRITE_FAILED" | "UNKNOWN_INTERNAL_ERROR" | 
/**
 *  Warning-grade only (architecture.md §24 Phase 3, §27): a
 *  `ReportAndKeepFirst` run published a non-empty duplicates-audit file
 *  in which at least one diverted duplicate carries a comment, NAG, or
 *  variation. See `crate::errors::annotated_duplicates_suppressed` and
 *  `crate::filesystem::duplicate_audit`.
 */
"ANNOTATED_DUPLICATES_SUPPRESSED";

/**
 *  See [`WarningRecord`]'s doc comment for why this now derives
 *  `Deserialize`/`Type` too.
 */
export type ErrorRecord = {
	code: ErrorCode,
	title: string,
	message: string,
	remediation: string | null,
	technicalId: string,
};

/**  A FEN-pattern position filter (design-02 row 23, §1.5.1 rendering map). */
export type FenPatternFilter = {
	pattern: string,
	/**
	 *  `false` → rendered as `FENPattern "<pattern>"`; `true` → rendered as
	 *  `FENPatternI "<pattern>"` (design-02 §1.5.1 rendering-map row: "FEN
	 *  pattern | `FENPattern \"<pattern>\"` (or `FENPatternI` when
	 *  side-agnostic requested)").
	 */
	bothSides: boolean,
};

/**
 *  Filter criteria for a job (architecture.md §9.2 `FilterPlan`; design-02
 *  §4.1 `filters`).
 */
export type FilterPlan = {
	/**
	 *  Tag/metadata criteria, rendered into `criteria/tags.txt` and passed
	 *  as `-t<path>` (design-02 row 19, §1.5.1). Different tags AND
	 *  together; multiple entries for the *same* tag OR together — this is
	 *  how both "either of these players" and "a date range" are expressed,
	 *  and it is the engine's semantics, not something this compiler
	 *  re-implements. `React never composes criteria syntax` (design-02
	 *  §1.5): a "year range" or "decisive result" UI control is expected to
	 *  already have expanded itself into the appropriate list of
	 *  [`TagRule`] entries (e.g. two `Result` rules, or two `Date` bound
	 *  rules) before this reaches Rust; the compiler's job is to render
	 *  each entry safely, not to invent the expansion.
	 */
	tagRules: TagRule[],
	moveBounds: MoveBounds | null,
	/**  `--checkmate` (design-02 row 25). */
	checkmateOnly: boolean,
	setupPolicy: SetupPolicy,
	/**
	 *  Rendered as a `FENPattern`/`FENPatternI` line inside the *same*
	 *  `criteria/tags.txt` file as `tag_rules` (design-02 row 23: "chosen
	 *  route" is the criteria file, not the standalone `--fenpattern` flag),
	 *  so `-t` is emitted whenever either this or `tag_rules` is non-empty.
	 */
	fenPattern: FenPatternFilter | null,
	/**
	 *  Opening-line filters, rendered into `criteria/variations.txt` and
	 *  passed as `-v<path>` (design-02 row 21, §1.5.2). Engine defaults
	 *  apply (match from move 1, permutations allowed; Decision D-12) — V1
	 *  does not expose `-P`/`--vanywhere`.
	 */
	textualVariations: string[],
	/**
	 *  Reserved for V1.1 (design-02 D-20). Must be empty in V1; the
	 *  compiler rejects any non-empty value as
	 *  `CompileError::UnsupportedOption` rather than attempting to interpret
	 *  raw engine arguments. `String` is a placeholder element type — V1.1
	 *  will replace this with a real validated-argument type when the
	 *  advanced-argument editor is designed.
	 */
	advancedArgs: string[],
};

/**
 *  One source PGN file, in the order the user added/reordered it.
 * 
 *  Design-02 delta (§4.1, binding per the coordinator's ruling): the
 *  architecture document's illustrative `InputFile` (§9.2) also carries
 *  `size_bytes`, `modified_at`, and `sha256`. Design-02's actual
 *  `JobSpecDto.inputs[]` shape does not — those richer, I/O-derived fields
 *  belong to the separate `InputInspectionDto` returned by the
 *  `inspect_inputs` command (design-02 §4.1), which is populated by
 *  filesystem probing the pure compiler must never perform. `JobSpec.inputs`
 *  carries only what the compiler actually needs: a path and its retention
 *  priority.
 */
export type InputFile = {
	path: string,
	displayName: string,
	/**
	 *  Zero-based retention priority. Input order **is** duplicate-retention
	 *  priority (architecture.md §10.7; design-02 T-5, §1.4): the compiler
	 *  appends input paths to argv in ascending `priority` order via a
	 *  stable sort. Design-02 §1.4 additionally states `validate_job`
	 *  rejects gaps/duplicates in the priority sequence — that hygiene
	 *  check belongs to the Phase 1b validation pipeline (design-02 §3.2),
	 *  not to this pure compiler, so `compile` accepts any `u32` values here
	 *  and merely orders by them.
	 */
	priority: number,
};

/**
 *  One `inspect_inputs` result row (design-02 §4.1: "per path: { path,
 *  displayName, sizeBytes, modifiedAt?, isReadable, extensionOk,
 *  warnings[] } / optional sha256 only when settings.hashInputs is on").
 */
export type InputInspectionDto = {
	path: string,
	displayName: string,
	sizeBytes: number | null,
	modifiedAt: string | null,
	isReadable: boolean,
	extensionOk: boolean,
	sha256: string | null,
	warnings: string[],
};

/**  `start_job` response (design-02 §4.1: `{ jobId, startedAt }`). */
export type JobAcceptedDto = {
	jobId: string,
	startedAt: string,
};

/**
 *  The closed `job://*` payload union (design-02 §4.2). `Clone` is required
 *  by `tauri::Emitter::emit`'s `Serialize + Clone` bound.
 * 
 *  **`rename_all_fields`, not just `rename_all` (load-bearing):** on an
 *  enum, plain `rename_all = "camelCase"` only camel-cases the *variant*
 *  names (the `type` tag's value: `"state"`, `"stage"`, ...) - it does
 *  **not** cascade into each struct variant's own field names. Without
 *  `rename_all_fields` here too, every event would serialize `job_id`
 *  verbatim (snake_case) while every other DTO in this crate uses camelCase,
 *  a real wire-format inconsistency that was caught by this module's own
 *  `job_event_serializes_job_id_as_camel_case_on_the_wire` test comparing
 *  actual `serde_json::to_string` output against the generated TypeScript
 *  (`specta`/`specta-serde` correctly reflect whichever behavior serde
 *  itself has, so a mismatch here would have been a real bug, not just a
 *  cosmetic one).
 */
export type JobEvent = { type: "state"; jobId: string; seq: number; state: JobStatus } | { type: "stage"; jobId: string; seq: number; stage: JobStage; message: string } | { type: "log"; jobId: string; seq: number; level: LogLevel; line: string } | { type: "metrics"; jobId: string; seq: number; metrics: ProcessingMetrics } | { type: "artifact"; jobId: string; seq: number; artifact: OutputArtifact } | { type: "completed"; jobId: string; seq: number; result: JobResult };

/**  `"process" | "validateOnly"` (design-02 §4.1). */
export type JobMode = "process" | "validateOnly";

/**
 *  `get_job` response: a live snapshot of the currently `Running`/
 *  `Cancelling` job, a terminal record reconstructed from the persisted
 *  workspace manifest, or (if the manifest itself is gone) the bounded
 *  history summary alone - see [`get_job`]'s doc comment for the exact
 *  fallback order. Fields absent for the reporting job's current state are
 *  `None` rather than fabricated (never a fake `EngineIdentity`/full metrics
 *  row for a summary-only fallback with none recorded).
 */
export type JobRecordDto = {
	jobId: string,
	name: string,
	status: JobStatus,
	startedAt: string,
	finishedAt: string | null,
	elapsedMs: number | null,
	engineVersion: string | null,
	artifacts: OutputArtifact[],
	metrics: ProcessingMetrics | null,
	warnings: WarningRecord[],
	error: ErrorRecord | null,
};

/**
 *  The terminal outcome of a single job run (architecture.md §9.3).
 * 
 *  Deliberately not `Deserialize` (Phase 1b correction): this type is
 *  outbound-only, as this struct's own original doc comment already said —
 *  dropping the derive (rather than just omitting `deny_unknown_fields`,
 *  Phase 1a's approach) makes that true at the type level, and is required
 *  anyway once `PublicError`/`JobWarning` stop being `Deserialize`.
 */
export type JobResult = {
	jobId: string,
	status: JobStatus,
	startedAt: string,
	finishedAt: string,
	elapsedMs: number,
	engine: EngineIdentity,
	artifacts: OutputArtifact[],
	metrics: ProcessingMetrics,
	warnings: JobWarning[],
	error: PublicError | null,
};

/**
 *  A complete, user-authored job description (architecture.md §9.2).
 * 
 *  This is the same shape that crosses the Tauri IPC boundary as
 *  `JobSpecDto` (design-02 §4.1) — there is deliberately no separate
 *  "wire" vs "domain" type in this codebase, so `#[serde(deny_unknown_fields)]`
 *  on every nested struct is load-bearing: it is the only thing standing
 *  between a typo'd frontend field and that field being silently ignored.
 */
export type JobSpec = {
	schemaVersion: number,
	id: string,
	name: string,
	inputs: InputFile[],
	output: OutputPlan,
	operations: OperationPlan,
	filters: FilterPlan,
	runtime: RuntimeOptions,
};

/**
 *  design-02 §2.3's stage sequence: `preparing` (workspace + criteria files
 *  written) -> `starting` (spawn) -> `processing` (first stderr bytes, or
 *  500 ms after spawn) -> `finalizing` (exit observed; postflight +
 *  publication) -> terminal.
 * 
 *  `Serialize`/`Type` (Phase 2a addition): Phase 1b deliberately kept this
 *  wire-format-free ("Phase 1b explicitly does not build Tauri commands or
 *  events - that is Phase 2", this module's own doc comment above) - the
 *  derives are added here, at the type's single definition site, rather
 *  than via a second mirror type in `commands/`, for the same
 *  single-source-of-truth reason the rest of the domain model does this
 *  (design-02 §4.3/D-17).
 */
export type JobStage = "preparing" | "starting" | "processing" | "finalizing";

/**
 *  Backend-owned runtime states (design-02 §2.1: "`Draft/Validating/Ready`
 *  are spec-lifecycle states held in frontend store...; only
 *  `Running/Cancelling` and the terminal states exist as backend-owned
 *  runtime state"). A [`JobResult`] is only ever produced for a job that
 *  reached `Running`, so those frontend-local states have no representation
 *  here.
 */
export type JobStatus = "running" | "cancelling" | "succeeded" | "failed" | "cancelled";

/**
 *  One row of `list_recent_jobs` (architecture.md §15.2's suggested `jobs`
 *  table, projected to JSON; design-02 §4.1 names the command but not this
 *  DTO's field list).
 */
export type JobSummaryDto = {
	jobId: string,
	name: string,
	status: JobStatus,
	startedAt: string,
	finishedAt: string | null,
	appVersion: string,
	engineVersion: string,
	errorCode: ErrorCode | null,
};

/**
 *  A non-fatal, warning-grade occurrence attached to an otherwise-terminal
 *  [`JobResult`] (e.g. `TEMP_CLEANUP_FAILED`, `HISTORY_WRITE_FAILED` —
 *  design-02 §5.1, §18.3). Reuses [`ErrorCode`] since design-02 treats
 *  warnings as drawn from the same closed taxonomy, just surfaced at a
 *  lower severity alongside a successful/terminal result rather than as the
 *  result's own `error`.
 * 
 *  Same privacy shape as [`PublicError`] and for the same reason: a warning
 *  `message` is just as user-facing as an error's, so it goes through the
 *  same redaction discipline in `crate::errors` rather than being built
 *  ad hoc wherever a warning is noticed.
 */
export type JobWarning = {
	code: ErrorCode,
	message: string,
};

export type LogLevel = "info" | "warn" | "error";

/**
 *  Move-count filter bounds, in whole moves (not ply) — design-02 row 24
 *  scopes V1 to `--maxmoves`/`--minmoves` only, not the ply variants.
 * 
 *  This type only *carries* the bounds; the safety-critical rule that
 *  `--maxmoves` must be emitted before `--minmoves` lives in
 *  `engine::command_compiler` (design-02 §0 finding 3, D-007 V-3, canonical
 *  order rule O-6b), because it is a property of argv construction, not of
 *  this data.
 */
export type MoveBounds = {
	min: number | null,
	max: number | null,
};

/**
 *  What processing to run (architecture.md §9.2 `OperationPlan`; design-02
 *  §4.1 `operations`).
 * 
 *  Design-02 delta (binding): the architecture document's illustrative
 *  `OperationPlan` (§9.2) has separate `merge: bool` / `validate: bool`
 *  flags. Design-02's actual DTO replaces both with a single closed `mode`
 *  (`JobMode`), which cannot express the contradictory `merge: false,
 *  validate: false` (or `true, true`) states the two-boolean form allowed.
 *  This module follows design-02.
 */
export type OperationPlan = {
	mode: JobMode,
	duplicates: DuplicatePolicy,
	cleanup: CleanupOptions,
	broken: BrokenOutput,
	eco: EcoOptions,
	outputNotation: OutputNotation,
	/**
	 *  Check file for the "New Games Against Master" preset: `-c<master.pgn>`
	 *  (architecture.md §12.2; design-02 flag table row 4, canonical order
	 *  O-5, Decision D-11, golden test G-9).
	 * 
	 *  Judgment call: design-02 §4.1's `JobSpecDto` does not include a field
	 *  for this, even though its own flag-mapping table (row 4), canonical
	 *  argument order (§1.4 O-5), and required golden test G-9 all depend on
	 *  one existing. This is treated as a gap in that DTO listing rather
	 *  than a deliberate omission, since dropping it would make G-9
	 *  impossible to implement. The compiler requires `.pgn` (case
	 *  insensitive) and an absolute path (row 4b, T-4), and requires
	 *  `duplicates != DuplicatePolicy::None` (row 4a: "`-c` alone does
	 *  nothing"), rejecting other combinations as `InvalidSpec` rather than
	 *  silently emitting an inert `-c` or silently upgrading the duplicate
	 *  policy on the caller's behalf.
	 */
	checkFile: string | null,
};

/**
 *  A published output artifact, as reported on [`super::JobResult`].
 * 
 *  Neither architecture.md §9 nor design-02 spells out this type's exact
 *  field list (design-02's `job://artifact` event payload references an
 *  `OutputArtifactDto` without defining it). This shape is a judgment call:
 *  the minimum needed to describe "what got written, and how big is it" for
 *  history/manifest display. Populating it is Phase 1b's job (it requires a
 *  `stat` call after publication); Phase 1a only defines the shape.
 */
export type OutputArtifact = {
	kind: ArtifactKind,
	path: string,
	sizeBytes: number,
};

/**
 *  Output move notation (design-02 row 29, D-13).
 * 
 *  V1 supports only [`OutputNotation::San`] (the engine's default; the
 *  compiler emits no `-W` token for it at all). [`OutputNotation::Uci`]
 *  exists solely so the capability-gated totality rule is exercisable
 *  end-to-end (golden test G-12: requesting it must produce
 *  `CompileError::UnsupportedOption`, never a silently-approximated
 *  command) — it is never advertised by the capability map and the
 *  compiler never emits a flag for it. Other notations the engine may
 *  support (e.g. long algebraic) are deliberately not enumerated here: their
 *  exact `-W<fmt>` spelling was not part of the source citations available
 *  for this task, and inventing one would violate the project's
 *  never-invent rule (DECISIONS-LEDGER.md header).
 */
export type OutputNotation = "san" | "uci";

/**  Where and how to publish job outputs (design-02 §4.1 `output`). */
export type OutputPlan = {
	/**
	 *  User-selected destination directory, as typed/browsed in the UI.
	 * 
	 *  The compiler never reads this field directly: `CompileLayout::destination_dir`
	 *  (engine::command_compiler) carries the *canonicalized* form of this
	 *  same directory, resolved by the application layer before compilation
	 *  (design-02 §1.1). Keeping the raw, pre-canonicalization value here is
	 *  still required for DTO round-tripping (history, the Review screen)
	 *  and for Phase 1b's `validate_job` to diagnose it.
	 */
	directory: string,
	baseName: string,
	/**
	 *  Whether to emit the merged/deduplicated main output (`-o`) at all.
	 *  `false` is a legitimate, non-error request (see
	 *  `engine::command_compiler` for the exact rules); it is not a variant
	 *  of validate-only mode, which is controlled by `OperationPlan.mode`.
	 */
	uniqueGames: boolean,
	/**
	 *  Whether a produced duplicates-audit temp file (see
	 *  `OperationPlan::duplicates`) should be *published* as a final
	 *  artifact. This is a genuinely separate axis from
	 *  `OperationPlan::duplicates`: the latter selects the engine's
	 *  duplicate-handling flag (`-d`/`-D`, or neither); this field only
	 *  decides whether a `-d` audit file that the engine produced as a side
	 *  effect is promoted to `final_outputs` or left as a discarded
	 *  temporary. `engine::command_compiler::compile` rejects combinations
	 *  where the two disagree in a way that could never produce a real file
	 *  (e.g. `Audit` requested under `DuplicatePolicy::None`) as
	 *  `CompileError::InvalidSpec`, rather than silently ignoring either
	 *  field (architecture.md §29).
	 */
	duplicateGames: DuplicateOutput,
	logFile: boolean,
	manifest: boolean,
	/**
	 *  When true, publish a duplicates-audit artifact even if it would be
	 *  empty (design-02 D-21 / architecture.md §11.6). Only meaningful when
	 *  `duplicate_games == Audit`.
	 */
	alwaysCreateAudit: boolean,
	conflictPolicy: ConflictPolicy,
	/**
	 *  Must be `true` for `conflict_policy == ReplaceAfterConfirmation` to
	 *  compile (design-02 §3.5: "requires `confirmed_replace: true` in the
	 *  spec, set only after an explicit UI confirmation dialog"). Checked by
	 *  the compiler, not merely by convention, since it is a pure
	 *  spec-internal consistency rule that needs no filesystem access.
	 */
	confirmedReplace: boolean,
};

export type PlannedArtifactDto = {
	kind: ArtifactKind,
	finalPath: string,
	/**
	 *  `None` for artifact kinds the pure compiler cannot predict a temp
	 *  path for (`LogText`/`ReportJson`/`ReportText`) - their temp paths are
	 *  only chosen at run time inside `jobs::run`'s
	 *  `build_artifacts_to_publish`, not by `command_compiler::compile`.
	 */
	temporaryPath: string | null,
};

/**
 *  Processing metrics (architecture.md §9.3).
 * 
 *  **Binding rule: never substitute `0` for a metric that could not be
 *  measured.** Every metric that is not *always* derivable is `Option<u64>`
 *  and must stay `None` rather than being guessed or defaulted. `input_files`
 *  and `input_bytes` are the two exceptions design-02 §2.4 calls out as
 *  always known ("from validation stats (always)") — they alone are plain
 *  `u64`, matching architecture.md §9.3's illustrative type exactly.
 * 
 *  `processed_games` is design-02 Decision D-19: architecture.md §9.3's
 *  struct has no live-progress field, but §13.6 requires honest live
 *  progress reporting, so design-02 adds this optional field for the
 *  in-flight `Games: N` tick count (as opposed to `input_games`, which is
 *  only known from the *final* summary line after the process exits 0).
 */
export type ProcessingMetrics = {
	inputFiles: number,
	inputBytes: number,
	/**
	 *  Live/last-seen progress count from `Games: N` stderr ticks, or the
	 *  final summary's `N` once the process exits (design-02 D-19).
	 */
	processedGames: number | null,
	/**
	 *  Final summary line's `M` (games actually parsed from normal inputs;
	 *  check-file games are excluded by the engine itself).
	 */
	inputGames: number | null,
	outputGames: number | null,
	duplicateGames: number | null,
	/**
	 *  Derivable only in the narrow cases design-02 §2.4 describes (no
	 *  filters, and duplicate policy is `None` or `ReportAndKeepFirst`);
	 *  `None` otherwise, since broken and filter-rejected games are
	 *  otherwise indistinguishable in the engine's own output.
	 */
	brokenGames: number | null,
	outputBytes: number | null,
};

/**
 *  The user-facing error shape (architecture.md §18.2; design-02 §5.2).
 * 
 *  **Phase 1b update:** design-02 §5.2 requires this struct's fields to be
 *  "private outside the module" that constructs it, with construction
 *  happening only "through per-code constructors" that enforce the
 *  redaction rule (no raw `Display`/`Debug` of internal errors, no
 *  backtraces, no raw OS error text in `message`). Phase 1a left every field
 *  `pub` as a deliberate placeholder (see the git history of this file) with
 *  an explicit note not to construct instances outside the real `errors/`
 *  module once it existed.
 * 
 *  `errors/` now exists (architecture.md's dependency-inward rule places it
 *  alongside `domain` — an application-layer module may depend on it, but
 *  `domain` itself must not depend on `tauri`/React/a particular engine
 *  version, and does not depend on `errors/` here either). To honor
 *  design-02's literal privacy requirement without domain importing an
 *  outer-layer module, the type stays defined here with genuinely private
 *  fields; the only constructor is [`PublicError::from_redacted_parts`],
 *  which is `pub(crate)` (Rust has no "friend module" visibility, so
 *  crate-wide is the strongest restriction achievable while keeping the
 *  type in `domain`) and is documented as reserved for `crate::errors`'s
 *  per-code constructor functions. Every other module — including this
 *  crate's own `jobs`/`filesystem` — must go through `crate::errors`, never
 *  build a `PublicError` by hand; that convention is what actually carries
 *  the redaction guarantee, since `from_redacted_parts` itself performs no
 *  redaction (it trusts its caller completely).
 * 
 *  Deliberately **not** `Deserialize`: this type is outbound-only (Rust
 *  constructs it, the frontend only ever receives it), and deriving
 *  `Deserialize` would reopen exactly the bypass this design closes — any
 *  code could reconstruct an arbitrary `PublicError` via
 *  `serde_json::from_str` instead of a struct literal.
 */
export type PublicError = {
	code: ErrorCode,
	title: string,
	message: string,
	remediation: string | null,
	logPath: string | null,
	technicalId: string,
};

/**  Execution-engine tuning that is not a filter or cleanup choice. */
export type RuntimeOptions = {
	/**
	 *  `-Z`: use a disk-backed duplicate table instead of in-memory hashing
	 *  (design-02 row 5). Intended for very large collections; irrelevant to
	 *  correctness, only to memory footprint.
	 */
	useExternalDuplicateTable: boolean,
	/**
	 *  Whether the orchestrator should attempt a postflight `[Event "`
	 *  streaming count of published artifacts to populate
	 *  `ProcessingMetrics::output_games`/`duplicate_games` (design-02 §2.4).
	 *  This does not change compiled argv at all — the engine has no flag
	 *  for it — but the compiler still consults it when computing
	 *  `MetricsPlan` (`engine::command_compiler`) so the plan reflects
	 *  what the caller actually asked to have measured.
	 */
	countOutputGames: boolean,
};

/**
 *  `scan_input_directory` request options - see
 *  `filesystem::folder_scan::ScanOptions` (the internal, non-IPC-facing
 *  twin this is converted into) for the full recursion-default rationale.
 *  A separate wire type rather than reusing that one directly for the same
 *  reason the rest of this codebase keeps `filesystem`/`engine` internals
 *  off the IPC boundary (design-02's "no wire type leaks an internal-only
 *  shape" convention - see `application::jobs::CommandPreviewDto`'s own
 *  doc comment for the identical reasoning applied to
 *  `engine::command_compiler::CompiledEngineCommand`).
 */
export type ScanInputDirectoryOptions = {
	/**
	 *  Whether to descend into subfolders. The frontend must default this
	 *  to `false` and surface it as an explicit "Include subfolders"
	 *  control - see `filesystem::folder_scan`'s module doc comment for why
	 *  non-recursive is the binding default.
	 */
	recursive: boolean,
	/**  The §11.2 "advanced override" for extensionless/non-`.pgn` files. */
	includeAllExtensions: boolean,
};

/**
 *  `get_settings`/`update_settings` response shape (architecture.md §15.1).
 * 
 *  `hash_inputs` (Phase 2a addition, not in architecture.md §15.1's
 *  illustrative example config): design-02 §4.1 gates
 *  `inspect_inputs`'s optional per-file `sha256` on "`settings.hashInputs`"
 *  as though it already existed, but no such field appears anywhere in
 *  architecture.md §15.1's settings shape. Rather than silently repurposing
 *  an unrelated existing flag (e.g. `rememberRecentFiles`, which is about a
 *  recent-files *list*, not hashing) or dropping the feature, this adds the
 *  field design-02 already assumes - architecture.md §15.3 independently
 *  supports it being optional ("Input hashing can be optional for very
 *  large files because it requires a full additional read"). Flagged in
 *  this crate's Phase 2a report for the coordinator to confirm or correct.
 */
export type SettingsDto = {
	schemaVersion: number,
	theme: Theme,
	defaultOutputDirectory: string | null,
	defaultConflictPolicy: ConflictPolicy,
	rememberRecentFiles: boolean,
	maxRecentJobs: number,
	showAdvancedCommand: boolean,
	updateChecks: UpdateCheckPolicy,
	hashInputs: boolean,
};

/**
 *  `update_settings(patch)` request shape. Every field is optional: absent
 *  = leave unchanged. `default_output_directory` is doubly-optional on
 *  purpose (`Option<Option<PathBuf>>`) so a patch can distinguish "don't
 *  touch this field" (absent) from "explicitly clear it back to null"
 *  (`null`) from "set it" (a string) - the one nullable field in
 *  [`SettingsDto`] needs the tri-state; every other field is non-nullable so
 *  a plain `Option<T>` (absent-vs-present) already says everything needed.
 *  Note for the generated TypeScript: `specta` cannot express the inner/
 *  outer distinction any more precisely than TS's own type system can, so
 *  the exported type reads as roughly `T | null | undefined` - the actual
 *  three-way behavior is documented here and exercised by this module's
 *  tests, not visible in the type alone.
 */
export type SettingsPatchDto = SettingsPatchDto_Serialize | SettingsPatchDto_Deserialize;

/**
 *  `update_settings(patch)` request shape. Every field is optional: absent
 *  = leave unchanged. `default_output_directory` is doubly-optional on
 *  purpose (`Option<Option<PathBuf>>`) so a patch can distinguish "don't
 *  touch this field" (absent) from "explicitly clear it back to null"
 *  (`null`) from "set it" (a string) - the one nullable field in
 *  [`SettingsDto`] needs the tri-state; every other field is non-nullable so
 *  a plain `Option<T>` (absent-vs-present) already says everything needed.
 *  Note for the generated TypeScript: `specta` cannot express the inner/
 *  outer distinction any more precisely than TS's own type system can, so
 *  the exported type reads as roughly `T | null | undefined` - the actual
 *  three-way behavior is documented here and exercised by this module's
 *  tests, not visible in the type alone.
 */
export type SettingsPatchDto_Deserialize = {
	theme?: Theme | null,
	defaultOutputDirectory?: string | null,
	defaultConflictPolicy?: ConflictPolicy | null,
	rememberRecentFiles?: boolean | null,
	maxRecentJobs?: number | null,
	showAdvancedCommand?: boolean | null,
	updateChecks?: UpdateCheckPolicy | null,
	hashInputs?: boolean | null,
};

/**
 *  `update_settings(patch)` request shape. Every field is optional: absent
 *  = leave unchanged. `default_output_directory` is doubly-optional on
 *  purpose (`Option<Option<PathBuf>>`) so a patch can distinguish "don't
 *  touch this field" (absent) from "explicitly clear it back to null"
 *  (`null`) from "set it" (a string) - the one nullable field in
 *  [`SettingsDto`] needs the tri-state; every other field is non-nullable so
 *  a plain `Option<T>` (absent-vs-present) already says everything needed.
 *  Note for the generated TypeScript: `specta` cannot express the inner/
 *  outer distinction any more precisely than TS's own type system can, so
 *  the exported type reads as roughly `T | null | undefined` - the actual
 *  three-way behavior is documented here and exercised by this module's
 *  tests, not visible in the type alone.
 */
export type SettingsPatchDto_Serialize = {
	theme?: Theme | null,
	defaultOutputDirectory?: string | null,
	defaultConflictPolicy?: ConflictPolicy | null,
	rememberRecentFiles?: boolean | null,
	maxRecentJobs?: number | null,
	showAdvancedCommand?: boolean | null,
	updateChecks?: UpdateCheckPolicy | null,
	hashInputs?: boolean | null,
};

/**  SetUp/FEN starting-position policy (design-02 row 26). */
export type SetupPolicy = 
/**
 *  Neither flag: games may start from the standard position or a
 *  `SetUp`/`FEN` tag.
 */
"any" | 
/**  `--nosetuptags`: only games starting from the standard position. */
"standardStartOnly" | 
/**  `--onlysetuptags`: only games with a `SetUp`/`FEN` tag. */
"setupOnly";

/**
 *  Recognized tag/pseudo-tag names for criteria rules (design-02 §1.5.1).
 * 
 *  Judgment call / known gap: design-02 states the engine recognizes "the 45
 *  predefined tags" but only names a subset by example
 *  (`Event, Site, Date, Round, White, Black, Result, WhiteElo, BlackElo,
 *  ECO, TimeControl, …`) plus the pseudo-tags `Player`, `Elo`, `EloDiff`
 *  (`FEN`/`FENPattern`/`FENPatternI` are handled separately via
 *  [`super::FenPatternFilter`], not as a `TagName`, per the "FilterPlan
 *  rendering map" table). This enum contains exactly the names design-02
 *  verifies by citation — no more. Extending it to the full 45-tag set
 *  requires a fresh, source-verified read of `lex.c:121-170`, which was not
 *  part of the material available for this task; inventing the remaining
 *  ~31 names to fill out the enum would violate the project's
 *  never-invent-never-placeholder rule (DECISIONS-LEDGER.md header). A free
 *  `String` field was deliberately rejected in favor of this closed enum
 *  because design-02 §4.1 explicitly calls `TagRuleDto` "typed: {tag, op,
 *  value} closed enums" and because inbound enums must be closed with no
 *  `other` catch-all (design-02 §4.3) — so the honest resolution is a
 *  smaller-but-real closed enum, not a falsely-complete one or an
 *  escape-hatch string.
 */
export type TagName = "Event" | "Site" | "Date" | "Round" | "White" | "Black" | "Result" | "WhiteElo" | "BlackElo" | "Eco" | "TimeControl" | 
/**  Pseudo-tag: matches if *either* color's player satisfies the rule. */
"Player" | 
/**  Pseudo-tag: matches if *either* color's Elo satisfies the rule. */
"Elo" | 
/**  Pseudo-tag: `|WhiteElo - BlackElo|`. */
"EloDiff";

/**
 *  A tag-rule comparison operator, or the absence of one (design-02 §1.5.1:
 *  `op ∈ { < <= <> > >= = =~ }`, no op = prefix match).
 * 
 *  UI wording for [`TagOp::Prefix`] must say "starts with", not "equals" —
 *  `strncmp`-based prefix matching means `Tal` matches `Talbot` (design-02
 *  §1.5.1).
 */
export type TagOp = 
/**  No operator: prefix ("starts with") match. */
"prefix" | "lt" | "le" | 
/**  `<>`: not-equal. */
"ne" | "gt" | "ge" | "eq" | 
/**  `=~`: POSIX basic regular expression, matched anywhere in the value. */
"regex";

/**
 *  One tag/metadata criterion line (design-02 §1.5.1 grammar:
 *  `<TagName> [<op>] "<value>"`).
 */
export type TagRule = {
	tag: TagName,
	op: TagOp,
	value: string,
};

export type Theme = "system" | "light" | "dark";

/**
 *  V1 ships exactly one policy (architecture.md §15.1's example config has
 *  `"updateChecks": "off"`, and V1 implements no update-check network call
 *  at all - architecture.md §16.2 "Do not transmit data or logs in Version
 *  1"). A real closed enum rather than a bare string, matching this
 *  project's everywhere-typed convention, with room to add `Manual`/
 *  `Automatic` variants in a later version without a breaking wire-shape
 *  change (only a widened enum).
 */
export type UpdateCheckPolicy = "off";

/**
 *  `validate_job` response. Adds `advisories` beyond design-02 §4.1's
 *  literal `{ status, errors, warnings, estimatedInputBytes, freeDiskBytes? }`
 *  sketch: `filesystem::validate::ValidationOutcome` intentionally carries
 *  free-text advisories (e.g. "these two inputs are the same file") that
 *  design-02's own DTO comment omits - dropping real signal would violate
 *  this project's "never silently drop signal" posture, the same posture
 *  `validate.rs`'s own doc comment invokes to justify the advisories
 *  existing at all. Flagged in this crate's Phase 2a report as a deliberate,
 *  justified deviation from the literal design-02 signature.
 */
export type ValidationReportDto = {
	status: ValidationStatus,
	errors: PublicError[],
	warnings: JobWarning[],
	advisories: string[],
	estimatedInputBytes: number,
	freeDiskBytes: number | null,
};

export type ValidationStatus = "ready" | "invalid";

/**
 *  `Deserialize`/`Type` (Phase 2a addition): `application::jobs::get_job`
 *  reads a completed job's `FinalManifest` back from
 *  `<jobs_root>/<job_id>/manifest.json` to answer `get_job` for a
 *  non-active job, and returns records of this exact shape to the frontend.
 *  This module's own doc comment already anticipated exactly this
 *  ("nothing in this codebase reads it back (that is a future
 *  history/persistence feature)").
 */
export type WarningRecord = {
	code: ErrorCode,
	message: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

