// SPDX-License-Identifier: GPL-3.0-or-later
//! Phase 5 integration tests (architecture.md §24 Phase 5 exit criterion:
//! "Each filter has at least one positive, negative, and combination test.").
//!
//! Mirrors `phase4_integration.rs`'s pattern exactly: real fixture PGNs, the
//! real orchestrator (`jobs::run_job`), the real checksum-verified bundled
//! sidecar — no mocks. Every expected match count below was produced by
//! actually running the pinned sidecar directly against these exact
//! fixtures during this task and reviewing the output, never hand-guessed
//! (architecture.md §4.3, §20.2; task instruction "Golden outputs must be
//! generated by the real engine and reviewed — never hand-written").
//!
//! Covers every §13.4 MVP filter: player (either)/White/Black, result
//! (specific + decisive-only), date/year range, Elo range (either/White/
//! Black), ECO code/range, minimum/maximum moves, checkmates-only, and
//! standard-start-only vs. include-SetUp/FEN. Also covers the task's
//! cross-cutting semantics (criteria-file encoding proven end to end, not
//! just on bytes; CR/LF/NUL rejection; escaping/containment; Unicode
//! round-trip; filters combined with cleanup and dedup; an all-excluded
//! filter publishing an honest, non-crashing empty result) and, as time
//! permitted (task §D, explicitly optional — see this file's final section
//! and the task report for what is/isn't wired into the UI), the two
//! advanced filters FEN pattern and textual opening-line variations.
//!
//! **Two findings from this phase correct earlier documentation** (full
//! evidence inline at each citation below):
//!
//! 1. (Headline; full evidence in `engine::criteria::tag_is_numeric`'s doc
//!    comment, `src-tauri/src/engine/criteria.rs`.) DECISIONS-LEDGER.md
//!    D-010 documented ECO's five broken relational/equality operators
//!    (`<`, `<=`, `>`, `>=`, `=`) as an ECO-specific fact. Fresh empirical
//!    testing for this phase proved it is a **general property of every
//!    non-numeric tag** — including, critically, `Result`. Before this
//!    phase's fix, `src/state/filterMapping.ts` compiled *every* Result
//!    checkbox on the Filters screen (White wins / Black wins / Draw /
//!    Other / Decisive-only) to `Result = "<value>"`, which silently
//!    matched **zero games, always**, for any job that used a Result
//!    filter — a live, shipped, ship-blocking bug, not a hypothetical one.
//!    Both the Rust compiler (`engine::criteria`) and the frontend
//!    (`filterMapping.ts`) are fixed in this phase; several tests below
//!    (`result_*`) are the real-engine proof of both the bug and the fix.
//! 2. (See `a_tag_missing_entirely_never_matches_even_when_every_criterion_is_not_equal`
//!    below.) design-02 §1.5.1 claims a game missing a criteria tag
//!    matches "unless every criterion on that tag is `<>`". Fresh empirical
//!    testing disproves the exception: a game missing a tag entirely never
//!    matches, `<>` included, with no carve-out. This one required no code
//!    fix — the shipped UI copy already states the simpler, correct,
//!    exception-free rule — but it is pinned here as a regression guard and
//!    a correction to the design document's own claim.

use std::ffi::OsString;
use std::path::{Path, PathBuf};

use uuid::Uuid;

use pgn_studio_lib::domain::{
    BrokenOutput, CleanupOptions, ConflictPolicy, DuplicateOutput, DuplicatePolicy, EcoOptions,
    EngineCapabilities, ErrorCode, FenPatternFilter, FilterPlan, InputFile, JobMode, JobSpec,
    JobStatus, MoveBounds, OperationPlan, OutputNotation, OutputPlan, RuntimeOptions, SetupPolicy,
    TagName, TagOp, TagRule, CURRENT_SCHEMA_VERSION,
};
use pgn_studio_lib::engine::sidecar::{startup_check, SidecarLocation};
use pgn_studio_lib::engine::EngineExecutable;
use pgn_studio_lib::filesystem::count_games_in_file;
use pgn_studio_lib::filesystem::workspace::workspace_root_for;
use pgn_studio_lib::jobs::{run_job, AppState, NullEventSink, RunJobContext};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("fixtures")
}

fn filters_fixture(name: &str) -> PathBuf {
    fixtures_dir().join("filters").join(name)
}

fn valid_fixture(name: &str) -> PathBuf {
    fixtures_dir().join("valid").join(name)
}

fn dup_fixture(name: &str) -> PathBuf {
    fixtures_dir().join("duplicates").join(name)
}

fn eco_file_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("resources/pgn-extract/eco.pgn")
}

async fn resolve_engine() -> (EngineExecutable, EngineCapabilities) {
    let result = startup_check(&SidecarLocation::dev_default()).await.expect(
        "the real, checksum-pinned sidecar must resolve and pass its startup self-test - if \
             this fails, `src-tauri/binaries/pgn-extract-x86_64-pc-windows-msvc.exe` is missing \
             or does not match the pinned checksum",
    );
    (result.engine, result.capabilities)
}

fn read_to_string(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
}

fn no_cleanup() -> CleanupOptions {
    CleanupOptions {
        remove_comments: false,
        remove_variations: false,
        remove_nags: false,
        remove_move_numbers: false,
        remove_results: false,
        remove_tags: vec![],
        reject_bad_results: false,
        fix_result_tags: false,
    }
}

fn no_filters() -> FilterPlan {
    FilterPlan {
        tag_rules: vec![],
        move_bounds: None,
        checkmate_only: false,
        setup_policy: SetupPolicy::Any,
        fen_pattern: None,
        textual_variations: vec![],
        advanced_args: vec![],
    }
}

/// Same shape/defaults as `phase4_integration.rs`'s `base_spec`: `Process`
/// mode, inputs in argument order, `Fail` conflict policy, no cleanup/
/// filters/ECO, no duplicate handling, no log/manifest artifacts. Each test
/// mutates only the fields its scenario cares about — almost always just
/// `filters`.
fn base_spec(inputs: Vec<PathBuf>, destination_dir: PathBuf, base_name: &str) -> JobSpec {
    JobSpec {
        schema_version: CURRENT_SCHEMA_VERSION,
        id: Uuid::new_v4(),
        name: "phase5-filters-integration-test".to_string(),
        inputs: inputs
            .into_iter()
            .enumerate()
            .map(|(i, path)| InputFile {
                display_name: path.display().to_string(),
                path,
                priority: i as u32,
            })
            .collect(),
        output: OutputPlan {
            directory: destination_dir,
            base_name: base_name.to_string(),
            unique_games: true,
            duplicate_games: DuplicateOutput::None,
            log_file: false,
            manifest: false,
            always_create_audit: false,
            conflict_policy: ConflictPolicy::Fail,
            confirmed_replace: false,
        },
        operations: OperationPlan {
            mode: JobMode::Process,
            duplicates: DuplicatePolicy::None,
            cleanup: no_cleanup(),
            broken: BrokenOutput::Discard,
            eco: EcoOptions { enabled: false },
            output_notation: OutputNotation::San,
            check_file: None,
        },
        filters: no_filters(),
        runtime: RuntimeOptions {
            use_external_duplicate_table: false,
            count_output_games: true,
        },
    }
}

fn tag_rule(tag: TagName, op: TagOp, value: &str) -> TagRule {
    TagRule {
        tag,
        op,
        value: value.to_string(),
    }
}

/// Runs `spec` through the real orchestrator and asserts it succeeded,
/// returning the result for further assertions (matches
/// `phase4_integration.rs`'s inline pattern, factored out here because
/// nearly every test in this file needs it).
async fn run_succeeding(
    spec: JobSpec,
    engine: &EngineExecutable,
    caps: &EngineCapabilities,
    jobs_root: &Path,
    eco_file: &Path,
) -> pgn_studio_lib::domain::JobResult {
    let state = AppState::new();
    let ctx = RunJobContext {
        caps,
        engine,
        jobs_root,
        eco_file,
    };
    let result = run_job(spec, &ctx, &state, &NullEventSink).await.unwrap();
    assert_eq!(result.status, JobStatus::Succeeded, "{:?}", result.error);
    result
}

// ===========================================================================
// A. Player (either color), White, Black
// ===========================================================================

/// Positive + the "no-op is prefix, not equality" trap in one test:
/// `Player "Tal"` matches White=Tal (G1), Black=Tal (G2), AND White=Talbot
/// (G3) — a real player named "Talbot" is not a typo, it is design-02's own
/// cited example that a no-op match is `strncmp`-based prefix matching.
#[tokio::test]
async fn player_either_color_matches_by_prefix_including_the_talbot_trap() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "player-either",
    );
    spec.filters.tag_rules = vec![tag_rule(TagName::Player, TagOp::Prefix, "Tal")];

    let result = run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("player-either.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 3);
    let text = read_to_string(&output_path);
    assert!(text.contains("[White \"Tal, Mikhail\"]"), "White = Tal");
    assert!(text.contains("[Black \"Tal, Mikhail\"]"), "Black = Tal");
    assert!(
        text.contains("[White \"Talbot, Toby\"]"),
        "\"Talbot\" must ALSO match a \"Tal\" prefix filter — this is not a bug"
    );
    assert!(
        !text.contains("Fischer") && !text.contains("Чайковский"),
        "unrelated players must be excluded (negative control)"
    );
    let _ = result;
}

/// Combination, dedicated to the `Player` (either-color) pseudo-tag
/// specifically: AND across three different tags (`Player`, `Result` OR
/// `Result`, `Date` range) in one criteria file, isolating exactly the two
/// games where Tal is decisive AND within the date range — excluding the
/// third "Tal" match (`Talbot`, a draw, outside no bound but wrong result)
/// from the earlier positive test.
#[tokio::test]
async fn player_either_combined_with_decisive_result_and_date_range() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "player-decisive-date-combo",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::Player, TagOp::Prefix, "Tal"),
        tag_rule(TagName::Result, TagOp::Prefix, "1-0"),
        tag_rule(TagName::Result, TagOp::Prefix, "0-1"),
        tag_rule(TagName::Date, TagOp::Ge, "1960.01.01"),
        tag_rule(TagName::Date, TagOp::Le, "1965.12.31"),
    ];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("player-decisive-date-combo.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        2,
        "G1 (Tal white, 1-0, 1960) and G2 (Tal black, 0-1, 1961) qualify; G3 (Talbot, a draw) \
         is excluded by the decisive-result criterion despite also matching the Player prefix"
    );
    let text = read_to_string(&output_path);
    assert!(text.contains("[Date \"1960.05.01\"]"));
    assert!(text.contains("[Date \"1961.03.15\"]"));
    assert!(
        !text.contains("[White \"Talbot, Toby\"]"),
        "the draw must be excluded even though its player name matches"
    );
}

/// White-scoped: matches only when Tal is specifically the White player —
/// the negative control here is the SAME player, as Black, in a different
/// game (G2), which must be excluded.
#[tokio::test]
async fn white_player_filter_excludes_the_same_player_as_black() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "white-player",
    );
    spec.filters.tag_rules = vec![tag_rule(TagName::White, TagOp::Prefix, "Tal")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let text = read_to_string(&dest.path().join("white-player.pgn"));
    assert_eq!(
        count_games_in_file(&dest.path().join("white-player.pgn")).unwrap(),
        2
    );
    assert!(text.contains("[White \"Tal, Mikhail\"]"));
    assert!(text.contains("[White \"Talbot, Toby\"]"));
    assert!(
        !text.contains("[White \"Botvinnik, Mikhail\"]"),
        "the game where Tal plays BLACK (White = Botvinnik) must be excluded"
    );
}

/// Black-scoped: the mirror image, and a combination with Date in the same
/// job (AND across different tags).
#[tokio::test]
async fn black_player_filter_combined_with_a_date_lower_bound() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "black-player-combo",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::Black, TagOp::Prefix, "Tal"),
        tag_rule(TagName::Date, TagOp::Ge, "1961.01.01"),
    ];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("black-player-combo.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 1);
    let text = read_to_string(&output_path);
    assert!(text.contains("[Black \"Tal, Mikhail\"]"));
    assert!(text.contains("[Date \"1961.03.15\"]"));
}

// ===========================================================================
// B. Result (specific value, decisive-only) — including the historical bug
// ===========================================================================

/// Positive + negative in one assertion: a specific Result value matches
/// exactly the games with that literal Result and excludes every other
/// Result value (draw, other-color win, unfinished).
#[tokio::test]
async fn result_specific_value_matches_only_that_exact_result() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "result-specific",
    );
    // "prefix" (no operator) — see this file's module doc comment and
    // `engine::criteria::tag_is_numeric` for why "eq" would silently match
    // nothing.
    spec.filters.tag_rules = vec![tag_rule(TagName::Result, TagOp::Prefix, "1-0")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("result-specific.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        3,
        "3 of the 6 fixture games have Result \"1-0\""
    );
    let text = read_to_string(&output_path);
    assert_eq!(text.matches("[Result \"1-0\"]").count(), 3);
    assert!(!text.contains("[Result \"0-1\"]"));
    assert!(!text.contains("[Result \"1/2-1/2\"]"));
    assert!(!text.contains("[Result \"*\"]"));
}

/// Decisive-only ORs two Result values together (same-tag OR semantics) and
/// excludes draws/unfinished games — the combination is "OR within one tag"
/// itself, which is exactly what `decisiveOnly` compiles to.
#[tokio::test]
async fn result_decisive_only_ors_the_two_win_values_and_excludes_draws() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "result-decisive",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::Result, TagOp::Prefix, "1-0"),
        tag_rule(TagName::Result, TagOp::Prefix, "0-1"),
    ];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("result-decisive.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 4);
    let text = read_to_string(&output_path);
    assert!(!text.contains("[Result \"1/2-1/2\"]"), "draw excluded");
    assert!(!text.contains("[Result \"*\"]"), "unfinished excluded");
}

/// **The headline empirical finding of this phase**, pinned end to end.
/// Deliberately bypasses the command compiler (which now correctly REJECTS
/// `Result` + `Eq` at compile time — see `command_compiler`'s capability/
/// structural validation and `engine::criteria`'s
/// `result_numeric_relational_operators_are_rejected` unit test) and spawns
/// the real sidecar directly with a hand-built criteria file, exactly as
/// `phase4_integration.rs`'s `eco_separated_form_is_catastrophic_empirical_proof`
/// does for its own historical hazard. Proves that `Result = "1-0"` — what
/// `src/state/filterMapping.ts` shipped before this phase's fix — silently
/// matches ZERO games, even though 3 of the 6 fixture games genuinely have
/// `Result "1-0"`, while the corrected no-op form matches all 3.
#[tokio::test]
async fn result_equality_operator_would_have_silently_matched_nothing_empirical_proof() {
    let (engine, _caps) = resolve_engine().await;
    let workdir = tempfile::tempdir().unwrap();
    let input_path = filters_fixture("players-results-dates.pgn");

    let buggy_criteria_path = workdir.path().join("buggy.txt");
    std::fs::write(&buggy_criteria_path, "Result = \"1-0\"\n").unwrap();
    let correct_criteria_path = workdir.path().join("correct.txt");
    std::fs::write(&correct_criteria_path, "Result \"1-0\"\n").unwrap();

    let run_with = |criteria: &Path, out_name: &str| {
        let out_path = workdir.path().join(out_name);
        let mut t_flag = OsString::from("-t");
        t_flag.push(criteria);
        let mut o_flag = OsString::from("-o");
        o_flag.push(&out_path);
        let output = std::process::Command::new(engine.path())
            .current_dir(workdir.path())
            .arg("-s")
            .arg("--summary")
            .arg(t_flag)
            .arg(o_flag)
            .arg(&input_path)
            .output()
            .expect("the real sidecar must spawn");
        assert_eq!(
            output.status.code(),
            Some(0),
            "engine run itself must succeed"
        );
        count_games_in_file(&out_path).unwrap_or(0)
    };

    let buggy_matches = run_with(&buggy_criteria_path, "buggy-out.pgn");
    let correct_matches = run_with(&correct_criteria_path, "correct-out.pgn");

    assert_eq!(
        buggy_matches, 0,
        "\"Result = \\\"1-0\\\"\" must silently match ZERO games even though 3 of 6 games \
         genuinely have that Result — this is the exact bug that shipped in \
         filterMapping.ts before this phase's fix"
    );
    assert_eq!(
        correct_matches, 3,
        "the corrected no-op/prefix form must match the 3 games that actually have Result \"1-0\""
    );
}

// ===========================================================================
// C. Date / year range
// ===========================================================================

/// Positive + negative: a `>=`/`<=` range keeps only games inside both
/// edges (design-02's rendering-map row).
#[tokio::test]
async fn date_range_keeps_only_games_inside_both_edges() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "date-range",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::Date, TagOp::Ge, "1960.01.01"),
        tag_rule(TagName::Date, TagOp::Le, "1965.12.31"),
    ];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("date-range.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 3);
    let text = read_to_string(&output_path);
    assert!(text.contains("[Date \"1960.05.01\"]"));
    assert!(text.contains("[Date \"1961.03.15\"]"));
    assert!(text.contains("[Date \"1965.07.07\"]"));
    assert!(
        !text.contains("[Date \"1972.09.01\"]") && !text.contains("[Date \"1975.11.20\"]"),
        "games outside the range must be excluded"
    );
}

/// **Verified semantics pinned end to end**: a bare-year lower/upper bound
/// (what a naive year-range UI control might be tempted to emit directly)
/// is auto-expanded by the compiler to a full date — proven here by
/// compiling a JobSpec with bare-year bounds through the REAL job pipeline
/// and observing the correct, inclusive-of-Dec-31 result.
#[tokio::test]
async fn date_bare_year_bound_is_auto_expanded_to_include_the_entire_year() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("date-edge-1999.pgn")],
        dest.path().to_path_buf(),
        "date-bare-year",
    );
    // A bare "1999" with Le — the compiler must expand this to
    // "1999.12.31", never emit it verbatim (engine::criteria::render_date_value).
    spec.filters.tag_rules = vec![tag_rule(TagName::Date, TagOp::Le, "1999")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("date-bare-year.pgn");
    let text = read_to_string(&output_path);
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        2,
        "both 1999 games (incl. the Dec 31 edge case) must be included, the 2000 game excluded"
    );
    assert!(text.contains("[Date \"1999.01.01\"]"));
    assert!(
        text.contains("[Date \"1999.12.31\"]"),
        "the Dec-31 edge case is exactly what a naive bare-year rendering would wrongly exclude"
    );
    assert!(!text.contains("[Date \"2000.01.01\"]"));
}

/// **Empirical proof of why the previous test matters.** Bypasses the
/// compiler (which never emits this form) and hand-builds the literal
/// buggy criteria line `Date <= "1999"`, spawning the real sidecar
/// directly — mirrors `phase4_integration.rs`'s catastrophic-proof style.
#[tokio::test]
async fn date_bare_year_upper_bound_would_have_silently_excluded_dec_31_empirical_proof() {
    let (engine, _caps) = resolve_engine().await;
    let workdir = tempfile::tempdir().unwrap();
    let input_path = filters_fixture("date-edge-1999.pgn");

    let buggy_path = workdir.path().join("buggy.txt");
    std::fs::write(&buggy_path, "Date <= \"1999\"\n").unwrap();
    let correct_path = workdir.path().join("correct.txt");
    std::fs::write(&correct_path, "Date <= \"1999.12.31\"\n").unwrap();

    let run_with = |criteria: &Path, out_name: &str| {
        let out_path = workdir.path().join(out_name);
        let mut t_flag = OsString::from("-t");
        t_flag.push(criteria);
        let mut o_flag = OsString::from("-o");
        o_flag.push(&out_path);
        let output = std::process::Command::new(engine.path())
            .current_dir(workdir.path())
            .arg("-s")
            .arg("--summary")
            .arg(t_flag)
            .arg(o_flag)
            .arg(&input_path)
            .output()
            .expect("the real sidecar must spawn");
        assert_eq!(output.status.code(), Some(0));
        count_games_in_file(&out_path).unwrap_or(0)
    };

    let buggy_matches = run_with(&buggy_path, "buggy-out.pgn");
    let correct_matches = run_with(&correct_path, "correct-out.pgn");

    assert_eq!(
        buggy_matches, 1,
        "the bare-year form \"Date <= \\\"1999\\\"\" silently excludes the Dec-31 1999 game — \
         only the Jan-1 game matches, because the engine defaults a missing month/day to 01/01"
    );
    assert_eq!(
        correct_matches, 2,
        "the full-date form matches both 1999 games, including Dec 31"
    );
}

// ===========================================================================
// D. Elo range (either player, White-scoped, Black-scoped)
// ===========================================================================

/// Positive + negative: the `Elo` pseudo-tag range excludes both a
/// too-low-rated game AND a game with no Elo tags at all (a game missing
/// the filtered tag never matches).
#[tokio::test]
async fn elo_either_scope_excludes_too_low_and_games_missing_the_tag_entirely() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("elo-tags.pgn")],
        dest.path().to_path_buf(),
        "elo-either",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::Elo, TagOp::Ge, "2600"),
        tag_rule(TagName::Elo, TagOp::Le, "2800"),
    ];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("elo-either.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 2);
    let text = read_to_string(&output_path);
    assert!(text.contains("[White \"Highrated, Hank\"]"));
    assert!(
        text.contains("[White \"Partial, Pat\"]"),
        "WhiteElo alone (2700) satisfies the range even though BlackElo is entirely absent — \
         \"some player satisfies all the bounds\" (design-02 §1.5.1)"
    );
    assert!(
        !text.contains("[White \"Midrated, Mona\"]"),
        "too low (2400/2380) must be excluded"
    );
    assert!(
        !text.contains("[White \"Norating, Nora\"]"),
        "a game with NO Elo tags at all must be excluded, not treated as a wildcard match"
    );
}

/// White-scoped vs Black-scoped are independent: `BlackElo` correctly
/// excludes the game whose *White* Elo would have satisfied an unscoped
/// filter, proving the scoping is real (not silently falling back to
/// either side).
#[tokio::test]
async fn white_and_black_scoped_elo_are_independent_and_combine_with_result() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("elo-tags.pgn")],
        dest.path().to_path_buf(),
        "elo-scoped",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::BlackElo, TagOp::Ge, "2600"),
        tag_rule(TagName::Result, TagOp::Prefix, "1-0"),
    ];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("elo-scoped.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        1,
        "only \"Highrated\" has BOTH BlackElo >= 2600 AND Result 1-0; \"Partial\" has Result \
         1-0 but no BlackElo tag at all, so it must be excluded here even though it satisfied \
         the unscoped Elo filter in the previous test"
    );
    let text = read_to_string(&output_path);
    assert!(text.contains("[White \"Highrated, Hank\"]"));
    assert!(!text.contains("[White \"Partial, Pat\"]"));
}

// ===========================================================================
// E. ECO code / range
// ===========================================================================

/// Positive + negative: an exact-code prefix and a "family" prefix
/// (multiple codes sharing the same leading characters).
#[tokio::test]
async fn eco_prefix_matches_a_single_code_and_a_whole_family() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();

    let mut single = base_spec(
        vec![filters_fixture("eco-codes.pgn")],
        dest.path().to_path_buf(),
        "eco-single",
    );
    single.filters.tag_rules = vec![tag_rule(TagName::Eco, TagOp::Prefix, "B10")];
    run_succeeding(single, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("eco-single.pgn")).unwrap(),
        1
    );

    let mut family = base_spec(
        vec![filters_fixture("eco-codes.pgn")],
        dest.path().to_path_buf(),
        "eco-family",
    );
    family.filters.tag_rules = vec![tag_rule(TagName::Eco, TagOp::Prefix, "B1")];
    run_succeeding(family, &engine, &caps, jobs_root.path(), &eco_file).await;
    let text = read_to_string(&dest.path().join("eco-family.pgn"));
    assert_eq!(
        count_games_in_file(&dest.path().join("eco-family.pgn")).unwrap(),
        2,
        "\"B1\" must match both B10 and B12"
    );
    assert!(text.contains("[ECO \"B10\"]") && text.contains("[ECO \"B12\"]"));
    assert!(
        !text.contains("[ECO \"B90\"]"),
        "B90 is not in the B1 family"
    );
}

/// `<>` (not-equal) — DECISIONS-LEDGER.md D-010, empirically reconfirmed
/// end to end via the real job pipeline (not just the raw engine, as D-010
/// itself checked).
#[tokio::test]
async fn eco_not_equal_excludes_only_the_named_code() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("eco-codes.pgn")],
        dest.path().to_path_buf(),
        "eco-ne",
    );
    spec.filters.tag_rules = vec![tag_rule(TagName::Eco, TagOp::Ne, "B10")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("eco-ne.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 4);
    assert!(!read_to_string(&output_path).contains("[ECO \"B10\"]"));
}

/// Combination: ECO family prefix AND a Result filter in the same criteria
/// file — proves the two rules AND together correctly (different tags).
#[tokio::test]
async fn eco_prefix_combined_with_result_filter() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("eco-codes.pgn")],
        dest.path().to_path_buf(),
        "eco-result-combo",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::Eco, TagOp::Prefix, "B"),
        tag_rule(TagName::Result, TagOp::Prefix, "1-0"),
    ];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("eco-result-combo.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        2,
        "B10 (1-0) and B12 (1-0) qualify; B90 is a B-code but Result 0-1, C50/A00 are not B-codes"
    );
    let text = read_to_string(&output_path);
    assert!(text.contains("[White \"Caro, Carl\"]"));
    assert!(text.contains("[White \"Advance, Ava\"]"));
}

/// **Correction to design-02 §1.5.1, with evidence.** design-02 states "a
/// game missing a criteria tag does not match (**unless every criterion on
/// that tag is `<>`**)" — implying an all-`<>` filter should match a game
/// that lacks the tag entirely (vacuous truth: "its ECO is not B10" reads
/// as true when there is no ECO at all). Fresh empirical testing disproves
/// the exception: a game with NO `ECO` tag never matches `ECO <> "B10"`,
/// exactly like every other operator — there is no `<>` carve-out. This
/// fixture isolates both halves in one assertion: a game whose `ECO`
/// genuinely differs (`C50`) DOES match, while a game with no `ECO` tag at
/// all does NOT, even though both would "vacuously" satisfy "not B10" under
/// design-02's stated rule. The existing UI copy (`FiltersScreen.tsx`,
/// `EloAndEcoFilters.tsx`) already states the simpler, exception-free rule
/// ("a game without the relevant tag is excluded by that filter") and
/// needed no correction — only design-02's own text did.
#[tokio::test]
async fn a_tag_missing_entirely_never_matches_even_when_every_criterion_is_not_equal() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("tag-missing-entirely.pgn")],
        dest.path().to_path_buf(),
        "tag-missing-not-equal",
    );
    spec.filters.tag_rules = vec![tag_rule(TagName::Eco, TagOp::Ne, "B10")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("tag-missing-not-equal.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        1,
        "exactly one game may match: the one whose ECO genuinely differs from B10"
    );
    let text = read_to_string(&output_path);
    assert!(
        text.contains("[White \"HasEco, Hana\"]"),
        "positive: ECO \"C50\" <> \"B10\" is genuinely true"
    );
    assert!(
        !text.contains("[White \"NoEco, Nadia\"]"),
        "negative: a game with NO ECO tag at all must NOT match, contradicting design-02's \
         stated \"<>\" exception"
    );
}

// ===========================================================================
// F. Minimum / maximum moves
// ===========================================================================

/// Positive + negative: a `[min, max]` range keeps only the game strictly
/// inside both edges.
#[tokio::test]
async fn move_bounds_range_keeps_only_the_game_inside_both_edges() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("move-bounds.pgn")],
        dest.path().to_path_buf(),
        "move-bounds-range",
    );
    spec.filters.move_bounds = Some(MoveBounds {
        min: Some(10),
        max: Some(15),
    });

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("move-bounds-range.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        1,
        "only the 15-move game is inside [10, 15]; 3-move and 30-move games excluded"
    );
    assert!(read_to_string(&output_path).contains("[White \"Medium, Mia\"]"));
}

/// Both bounds are independently optional: min-only and max-only each keep
/// a different pair of the three games.
#[tokio::test]
async fn move_bounds_min_only_and_max_only_are_independent() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();

    let mut min_only = base_spec(
        vec![filters_fixture("move-bounds.pgn")],
        dest.path().to_path_buf(),
        "move-bounds-min-only",
    );
    min_only.filters.move_bounds = Some(MoveBounds {
        min: Some(10),
        max: None,
    });
    run_succeeding(min_only, &engine, &caps, jobs_root.path(), &eco_file).await;
    let min_text = read_to_string(&dest.path().join("move-bounds-min-only.pgn"));
    assert_eq!(
        count_games_in_file(&dest.path().join("move-bounds-min-only.pgn")).unwrap(),
        2
    );
    assert!(min_text.contains("Medium, Mia") && min_text.contains("Longgame, Leo"));
    assert!(!min_text.contains("Short, Sam"));

    let mut max_only = base_spec(
        vec![filters_fixture("move-bounds.pgn")],
        dest.path().to_path_buf(),
        "move-bounds-max-only",
    );
    max_only.filters.move_bounds = Some(MoveBounds {
        min: None,
        max: Some(15),
    });
    run_succeeding(max_only, &engine, &caps, jobs_root.path(), &eco_file).await;
    let max_text = read_to_string(&dest.path().join("move-bounds-max-only.pgn"));
    assert_eq!(
        count_games_in_file(&dest.path().join("move-bounds-max-only.pgn")).unwrap(),
        2
    );
    assert!(max_text.contains("Short, Sam") && max_text.contains("Medium, Mia"));
    assert!(!max_text.contains("Longgame, Leo"));
}

/// Combination: move bounds (an argv-flag filter) AND a Result tag rule (a
/// criteria-file filter) in the same job — proves the two different
/// filtering mechanisms compose correctly.
#[tokio::test]
async fn move_bounds_combined_with_result_tag_rule() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("move-bounds.pgn")],
        dest.path().to_path_buf(),
        "move-bounds-result-combo",
    );
    spec.filters.move_bounds = Some(MoveBounds {
        min: Some(10),
        max: Some(20),
    });
    spec.filters.tag_rules = vec![tag_rule(TagName::Result, TagOp::Prefix, "1-0")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("move-bounds-result-combo.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        1,
        "the 3-move game fails both bounds and result; the 30-move game has the right result \
         but fails the upper bound (30 > 20); only the 15-move game satisfies both"
    );
    assert!(read_to_string(&output_path).contains("Medium, Mia"));
}

/// **DECISIONS-LEDGER.md D-007 V-3, end to end.** The real, compiled job
/// (correct `--maxmoves`-before-`--minmoves` order) gives the right answer;
/// this test additionally reproduces the reversed-order hazard directly
/// against the real engine (bypassing the compiler, which structurally
/// cannot emit the wrong order) to prove *why* the order rule matters, not
/// merely that the compiler happens to emit one particular order.
#[tokio::test]
async fn move_bounds_reversed_argument_order_silently_admits_a_too_long_game_empirical_proof() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();

    // The real, compiled, end-to-end path: correct order, correct result.
    let bounds = MoveBounds {
        min: Some(10),
        max: Some(15),
    };
    let mut spec = base_spec(
        vec![filters_fixture("move-bounds.pgn")],
        dest.path().to_path_buf(),
        "move-bounds-correct-e2e",
    );
    spec.filters.move_bounds = Some(bounds);
    // Confirm this fixture is inside the empirically verified trigger zone
    // (max < 2*min - 1) so a future edit to these values can't silently
    // stop reproducing the hazard without this test noticing. Computed from
    // `bounds`'s own fields (not restated as literals), matching
    // `golden_tests.rs`'s g8 test, so this can't degrade into an
    // always-true constant assertion (clippy `assertions_on_constants`).
    let min = bounds.min.expect("fixture always sets min");
    let max = bounds.max.expect("fixture always sets max");
    assert!(
        max < 2 * min - 1,
        "test fixture must be inside the verified trigger zone (max < 2*min - 1), got \
         min={min} max={max}"
    );
    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("move-bounds-correct-e2e.pgn")).unwrap(),
        1,
        "compiled (correct-order) end-to-end run must keep only the 15-move game"
    );

    // The raw, reversed-order hazard: bypasses the compiler entirely.
    let workdir = tempfile::tempdir().unwrap();
    let input_path = filters_fixture("move-bounds.pgn");
    let out_path = workdir.path().join("reversed-out.pgn");
    let mut o_flag = OsString::from("-o");
    o_flag.push(&out_path);
    let run = std::process::Command::new(engine.path())
        .current_dir(workdir.path())
        .arg("-s")
        .arg("--summary")
        .arg("--minmoves")
        .arg("10")
        .arg("--maxmoves")
        .arg("15")
        .arg(o_flag)
        .arg(&input_path)
        .output()
        .expect("the real sidecar must spawn");
    assert_eq!(
        run.status.code(),
        Some(0),
        "the engine still exits 0 — silent, not loud"
    );
    let stderr = String::from_utf8_lossy(&run.stderr);
    assert!(
        stderr.contains("Upper bound of ply limit is smaller than the lower bound"),
        "the engine's own warning must be present on stderr, got: {stderr}"
    );
    assert_eq!(
        count_games_in_file(&out_path).unwrap_or(0),
        2,
        "reversed order silently drops the upper bound: the 30-move game wrongly survives a \
         [10, 15] filter alongside the 15-move game"
    );
}

// ===========================================================================
// G. Checkmates only
// ===========================================================================

/// Positive + negative: `--checkmate` is a positional check (did the game
/// actually end in checkmate), not a `Result`-tag check — the negative
/// control here has a normal decisive `Result` tag but does not end `#`.
#[tokio::test]
async fn checkmate_only_keeps_actual_checkmates_not_merely_decisive_results() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("checkmates.pgn")],
        dest.path().to_path_buf(),
        "checkmate-only",
    );
    spec.filters.checkmate_only = true;

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("checkmate-only.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 2);
    let text = read_to_string(&output_path);
    assert!(text.contains("[White \"Blunder, Bob\"]"), "Fool's mate");
    assert!(
        text.contains("[White \"Scholar, Sally\"]"),
        "Scholar's mate"
    );
    assert!(
        !text.contains("[White \"Resign, Rita\"]"),
        "a decisive Result with no actual checkmate must be excluded"
    );
}

/// Combination: checkmate-only AND a Result filter isolates exactly the
/// checkmate that also has that Result (both games in the fixture end in
/// checkmate, but only one is a Black win).
#[tokio::test]
async fn checkmate_only_combined_with_result_isolates_one_specific_game() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("checkmates.pgn")],
        dest.path().to_path_buf(),
        "checkmate-result-combo",
    );
    spec.filters.checkmate_only = true;
    spec.filters.tag_rules = vec![tag_rule(TagName::Result, TagOp::Prefix, "0-1")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("checkmate-result-combo.pgn");
    assert_eq!(
        count_games_in_file(&output_path).unwrap(),
        1,
        "only Fool's mate is BOTH an actual checkmate AND a 0-1 result"
    );
    assert!(read_to_string(&output_path).contains("[White \"Blunder, Bob\"]"));
}

// ===========================================================================
// H. Standard-start-only vs. include SetUp/FEN
// ===========================================================================

/// Positive + negative: `standardStartOnly` excludes both SetUp/FEN games,
/// keeping every standard-start game.
#[tokio::test]
async fn standard_start_only_excludes_every_setup_fen_game() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![
            valid_fixture("setup-fen.pgn"),
            valid_fixture("single-game.pgn"),
            valid_fixture("multi-game-results.pgn"),
        ],
        dest.path().to_path_buf(),
        "standard-only",
    );
    spec.filters.setup_policy = SetupPolicy::StandardStartOnly;

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("standard-only.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 4);
    let text = read_to_string(&output_path);
    assert!(!text.contains("[White \"Ivanov, Igor\"]"));
    assert!(!text.contains("[White \"Kwon, Ki\"]"));
}

/// The mirror image, combined with a player filter to isolate one specific
/// SetUp game out of the two.
#[tokio::test]
async fn setup_only_keeps_only_setup_fen_games_combined_with_a_player_filter() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();

    // First, without the player filter: both SetUp games.
    let mut both = base_spec(
        vec![
            valid_fixture("setup-fen.pgn"),
            valid_fixture("single-game.pgn"),
            valid_fixture("multi-game-results.pgn"),
        ],
        dest.path().to_path_buf(),
        "setup-only-both",
    );
    both.filters.setup_policy = SetupPolicy::SetupOnly;
    run_succeeding(both, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("setup-only-both.pgn")).unwrap(),
        2,
        "negative control: standard-start games must be excluded"
    );

    // Combination: setupOnly AND White prefix "Ivanov" isolates one game.
    let mut combo = base_spec(
        vec![
            valid_fixture("setup-fen.pgn"),
            valid_fixture("single-game.pgn"),
            valid_fixture("multi-game-results.pgn"),
        ],
        dest.path().to_path_buf(),
        "setup-only-combo",
    );
    combo.filters.setup_policy = SetupPolicy::SetupOnly;
    combo.filters.tag_rules = vec![tag_rule(TagName::White, TagOp::Prefix, "Ivanov")];
    run_succeeding(combo, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("setup-only-combo.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 1);
    assert!(read_to_string(&output_path).contains("[White \"Ivanov, Igor\"]"));
}

/// `Any` (neither flag) is the baseline: every game, standard-start or not.
#[tokio::test]
async fn any_setup_policy_keeps_every_game() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let spec = base_spec(
        vec![
            valid_fixture("setup-fen.pgn"),
            valid_fixture("single-game.pgn"),
            valid_fixture("multi-game-results.pgn"),
        ],
        dest.path().to_path_buf(),
        "setup-any",
    );
    assert_eq!(spec.filters.setup_policy, SetupPolicy::Any);

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("setup-any.pgn")).unwrap(),
        6
    );
}

// ===========================================================================
// I. Cross-cutting semantics: encoding, escaping, Unicode, safety
// ===========================================================================

/// **Not just a unit test on bytes.** Runs a real filtered job, then reads
/// the ACTUAL `criteria/tags.txt` bytes the orchestrator wrote to the
/// job's real workspace (the same file the real sidecar was pointed at via
/// `-t`) and asserts no UTF-8 BOM / no CR — AND, in the same test, that the
/// job's output was genuinely filtered (3 of 6 games), which is only
/// possible if the on-disk file the engine actually read was not corrupted
/// by a BOM (a BOM would make `taglines.c` silently ignore every criterion
/// and run the job completely unfiltered — design-02 §1.5 — so an
/// unfiltered 6/6 result here would itself be the regression signal).
#[tokio::test]
async fn criteria_file_on_disk_has_no_bom_or_cr_and_the_job_actually_filters() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "criteria-encoding",
    );
    spec.filters.tag_rules = vec![tag_rule(TagName::Player, TagOp::Prefix, "Tal")];
    let job_id = spec.id;

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;

    // Proof #1: the job genuinely filtered (would be 6/6 if the on-disk
    // file were silently ignored due to a BOM).
    assert_eq!(
        count_games_in_file(&dest.path().join("criteria-encoding.pgn")).unwrap(),
        3,
        "a BOM regression would silently run this job UNFILTERED (6/6), not fail loudly"
    );

    // Proof #2: the actual bytes on disk, read independently of anything
    // the renderer's own unit tests assert.
    let workspace_root = workspace_root_for(jobs_root.path(), job_id);
    let criteria_path = workspace_root.join("criteria").join("tags.txt");
    let bytes = std::fs::read(&criteria_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", criteria_path.display()));
    assert!(
        !bytes.starts_with(&[0xEF, 0xBB, 0xBF]),
        "the real on-disk criteria file the engine was pointed at must not start with a UTF-8 BOM"
    );
    assert!(
        !bytes.contains(&b'\r'),
        "the real on-disk criteria file must contain no CR bytes"
    );
    assert!(bytes.ends_with(b"\n"), "must end with a trailing LF");
    assert_eq!(
        String::from_utf8(bytes).unwrap(),
        "Player \"Tal\"\n",
        "exact expected content"
    );
}

/// CR/LF/NUL in a filter value must be rejected at validation, before the
/// engine ever runs — never truncated, never silently accepted. Proven at
/// the `run_job` level (not just `engine::criteria`'s unit tests): the job
/// fails with `INVALID_JOB_SPEC` and no workspace is ever created (i.e. no
/// partially-written / corrupted criteria file is left behind).
#[tokio::test]
async fn criteria_value_with_embedded_newline_is_rejected_before_the_engine_ever_runs() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "criteria-cr-lf-nul",
    );
    spec.filters.tag_rules = vec![tag_rule(
        TagName::Player,
        TagOp::Prefix,
        "Tal\nECO \">\"\"A00",
    )];
    let job_id = spec.id;

    let state = AppState::new();
    let ctx = RunJobContext {
        caps: &caps,
        engine: &engine,
        jobs_root: jobs_root.path(),
        eco_file: &eco_file,
    };
    let result = run_job(spec, &ctx, &state, &NullEventSink).await.unwrap();

    assert_eq!(result.status, JobStatus::Failed);
    assert_eq!(
        result.error.as_ref().map(|e| e.code()),
        Some(ErrorCode::InvalidJobSpec)
    );
    assert!(
        !dest.path().join("criteria-cr-lf-nul.pgn").exists(),
        "no output must ever be published for a rejected spec"
    );
    assert!(
        !workspace_root_for(jobs_root.path(), job_id).exists(),
        "the job must fail before the workspace (and therefore any criteria file) is ever \
         created — never write a partial/corrupted file"
    );
}

/// Positive: a filter value containing an embedded double-quote AND a
/// backslash round-trips through Rust's criteria-file escaping and matches
/// the real game whose PGN-encoded tag value contains those exact
/// characters.
#[tokio::test]
async fn filter_value_with_quotes_and_backslashes_matches_correctly() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("escaping.pgn")],
        dest.path().to_path_buf(),
        "escaping-positive",
    );
    // The literal (unescaped) value; engine::criteria::escape_value is
    // solely responsible for making this safe inside the criteria file.
    spec.filters.tag_rules = vec![tag_rule(
        TagName::Event,
        TagOp::Prefix,
        "Round \"Robin\" Stage C:\\Games",
    )];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("escaping-positive.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 1);
    assert!(read_to_string(&output_path).contains("[White \"Escaper, Eddie\"]"));
}

/// Negative: a similar-but-not-identical value (different drive letter)
/// must NOT match — proves the escaping isn't accidentally over-permissive
/// (e.g. collapsing the backslash into a wildcard).
#[tokio::test]
async fn filter_value_with_quotes_and_backslashes_does_not_false_positive_match() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("escaping.pgn")],
        dest.path().to_path_buf(),
        "escaping-negative",
    );
    spec.filters.tag_rules = vec![tag_rule(
        TagName::Event,
        TagOp::Prefix,
        "Round \"Robin\" Stage D:\\Games",
    )];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("escaping-negative.pgn")).unwrap(),
        0
    );
}

/// **Cannot break out of the criteria file.** An adversarial value crafted
/// to look like it might close the quoted string and inject a new
/// criterion is combined with a second, independent, real criterion
/// (`Black` prefix "Botvinnik", which matches 2/6 games on its own — see
/// the control assertion below). If escaping ever regressed, the malformed
/// first line would silently terminate ALL criteria parsing
/// (`taglines.c:239-242`, design-02 §1.5) and the job would run completely
/// UNFILTERED (6/6), which is sharply distinguishable from both the
/// correct "0 games" (rule 1 matches nothing, ANDed with anything is still
/// nothing) and the control's "2 games" (rule 2 alone).
#[tokio::test]
async fn an_adversarial_quote_cannot_truncate_a_later_criterion_in_the_same_file() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();

    // Control: rule 2 alone, to establish its real, independent effect.
    let mut control = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "adversarial-control",
    );
    control.filters.tag_rules = vec![tag_rule(TagName::Black, TagOp::Prefix, "Botvinnik")];
    run_succeeding(control, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("adversarial-control.pgn")).unwrap(),
        2,
        "sanity baseline: Black=Botvinnik alone matches 2 of 6 games"
    );

    // The adversarial pair: rule 1 is crafted to contain a quote,
    // backslash, and text that resembles a second criterion, all on one
    // logical line; rule 2 is the exact same real criterion as the control.
    let mut adversarial = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "adversarial-combo",
    );
    adversarial.filters.tag_rules = vec![
        tag_rule(TagName::Event, TagOp::Prefix, "X\" ECO \">\"A00"),
        tag_rule(TagName::Black, TagOp::Prefix, "Botvinnik"),
    ];
    run_succeeding(adversarial, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("adversarial-combo.pgn")).unwrap(),
        0,
        "correct behavior: rule 1 (garbage Event prefix) matches nothing on its own, so the AND \
         combination matches nothing — a regression that broke escaping would instead show 6 \
         (unfiltered), not 2 (rule 2 silently alone) and not 0"
    );
}

/// Unicode player names survive the round trip through the UTF-8 criteria
/// file and match correctly; a Latin-script filter correctly does not
/// match the Unicode-named game (negative control).
#[tokio::test]
async fn unicode_player_name_round_trips_and_matches() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "unicode-player",
    );
    spec.filters.tag_rules = vec![tag_rule(TagName::Player, TagOp::Prefix, "Чайковский")];

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let output_path = dest.path().join("unicode-player.pgn");
    assert_eq!(count_games_in_file(&output_path).unwrap(), 1);
    assert!(read_to_string(&output_path).contains("[White \"Чайковский, Пётр\"]"));

    // Negative control on the SAME fixture: a Latin filter must not match
    // the Unicode-named game (and vice versa is already proven by the
    // 1-of-6 count above).
    let mut latin = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "unicode-player-negative",
    );
    latin.filters.tag_rules = vec![tag_rule(TagName::Player, TagOp::Prefix, "Tal")];
    run_succeeding(latin, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert!(
        !read_to_string(&dest.path().join("unicode-player-negative.pgn")).contains("Чайковский"),
        "a Latin \"Tal\" filter must not match the Cyrillic-named game"
    );
}

/// Filters combined with cleanup AND deduplication in one job: a decisive-
/// result filter, `-C` comment removal, and `ReportAndKeepFirst`
/// deduplication all apply together correctly in a single pass.
#[tokio::test]
async fn filters_combine_with_cleanup_and_deduplication_in_one_job() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![
            filters_fixture("players-results-dates.pgn"),
            dup_fixture("order-a.pgn"),
            dup_fixture("order-b.pgn"),
            valid_fixture("long-comment.pgn"),
        ],
        dest.path().to_path_buf(),
        "combo-filter-cleanup-dedup",
    );
    spec.filters.tag_rules = vec![
        tag_rule(TagName::Result, TagOp::Prefix, "1-0"),
        tag_rule(TagName::Result, TagOp::Prefix, "0-1"),
    ];
    spec.operations.cleanup.remove_comments = true;
    spec.operations.duplicates = DuplicatePolicy::ReportAndKeepFirst;
    spec.output.duplicate_games = DuplicateOutput::Audit;

    run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;
    let main_path = dest.path().join("combo-filter-cleanup-dedup.pgn");
    let audit_path = dest
        .path()
        .join("combo-filter-cleanup-dedup.duplicates.pgn");
    assert_eq!(
        count_games_in_file(&main_path).unwrap(),
        6,
        "4 decisive games from players-results-dates.pgn + order-a (first copy) + long-comment"
    );
    assert_eq!(
        count_games_in_file(&audit_path).unwrap(),
        1,
        "order-b is diverted as the later duplicate copy"
    );
    let main_text = read_to_string(&main_path);
    assert!(
        !main_text.contains("This is a"),
        "the long comment must be stripped by -C even in a job that also filters and dedupes"
    );
    assert!(
        main_text.contains("[White \"Anderson, Ann\"]"),
        "order-a kept"
    );
    assert!(
        !main_text.contains("[White \"Baxter, Bo\"]"),
        "order-b diverted to the audit file, not the main output"
    );
    assert!(read_to_string(&audit_path).contains("[White \"Baxter, Bo\"]"));
}

/// A filter that matches nothing publishes an empty-but-valid output and
/// reports honest (not fabricated, not hidden) metrics — never a crash,
/// never a false success that hides the fact nothing matched.
#[tokio::test]
async fn a_filter_matching_nothing_publishes_an_empty_output_honestly() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let mut spec = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "empty-result",
    );
    spec.filters.tag_rules = vec![tag_rule(TagName::Player, TagOp::Prefix, "Nobody")];

    let result = run_succeeding(spec, &engine, &caps, jobs_root.path(), &eco_file).await;

    assert_eq!(result.status, JobStatus::Succeeded, "not a crash");
    assert!(result.error.is_none(), "not a false failure either");
    let output_path = dest.path().join("empty-result.pgn");
    assert!(
        output_path.exists(),
        "the main output still publishes even when empty (design-02 D-21)"
    );
    assert_eq!(count_games_in_file(&output_path).unwrap(), 0);
    assert_eq!(
        result.metrics.output_games,
        Some(0),
        "honest: explicitly zero, not None (which would look like \"not measured\") and not \
         some fabricated nonzero count (\"false success\")"
    );
    assert_eq!(
        result.metrics.input_games,
        Some(6),
        "honest: the engine really did process 6 games, it just matched none of them"
    );
}

// ===========================================================================
// J. Advanced filters (task §D, explicitly optional): FEN pattern and
//    textual opening-line variations.
//
//    NOT exposed in the Filters-screen UI in this phase — see this crate's
//    `src/state/filterMapping.ts`, which unconditionally hardcodes
//    `fenPattern: null` and `textualVariations: []` regardless of any
//    draft state (there is no draft state for them at all: `FilterDraft`
//    has no corresponding fields, and no Filters-screen component renders
//    a control for either). This matches architecture.md §13.4's actual
//    MVP filter list, which names neither. The tests below prove the
//    backend plumbing (JobSpec -> criteria file -> real engine) genuinely
//    works end to end regardless, exercised directly through JobSpec/
//    run_job the same way golden_tests.rs exercises other compiler-only
//    paths, per the task's explicit instruction to implement these fully
//    ("with the same positive/negative/combination coverage") rather than
//    leave them half-wired, while being explicit that no UI reaches them.
// ===========================================================================

/// Positive + negative: an exact (no-wildcard) FEN pattern for the standard
/// starting position matches every standard-start game and no SetUp/FEN
/// game.
#[tokio::test]
async fn fen_pattern_exact_standard_start_matches_standard_games_only() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    let standard_start = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR";

    let mut positive = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "fen-standard-positive",
    );
    positive.filters.fen_pattern = Some(FenPatternFilter {
        pattern: standard_start.to_string(),
        both_sides: false,
    });
    run_succeeding(positive, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("fen-standard-positive.pgn")).unwrap(),
        6,
        "every game in this fixture begins from the standard position"
    );

    let mut negative = base_spec(
        vec![valid_fixture("setup-fen.pgn")],
        dest.path().to_path_buf(),
        "fen-standard-negative",
    );
    negative.filters.fen_pattern = Some(FenPatternFilter {
        pattern: standard_start.to_string(),
        both_sides: false,
    });
    run_succeeding(negative, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("fen-standard-negative.pgn")).unwrap(),
        0,
        "neither SetUp/FEN game ever passes through the standard starting position"
    );
}

/// A wildcard pattern matches a transient (mid-game) position reached by
/// most, but not all, games — proving genuine fuzzy/positional matching,
/// not just a move-0 special case — and combines with a tag rule in the
/// same criteria file.
#[tokio::test]
async fn fen_pattern_wildcard_matches_a_transient_position_and_combines_with_a_tag_rule() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();
    // Rank 3 (from White's side): a White knight specifically on f3, any-
    // thing else anywhere. Matches every game in the fixture whose White
    // knight visits f3 at any point during the game.
    let knight_on_f3 = "*/*/*/*/*/?????N??/????????/*";

    let mut positive = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "fen-wildcard-positive",
    );
    positive.filters.fen_pattern = Some(FenPatternFilter {
        pattern: knight_on_f3.to_string(),
        both_sides: false,
    });
    run_succeeding(positive, &engine, &caps, jobs_root.path(), &eco_file).await;
    let text = read_to_string(&dest.path().join("fen-wildcard-positive.pgn"));
    assert_eq!(
        count_games_in_file(&dest.path().join("fen-wildcard-positive.pgn")).unwrap(),
        5,
        "5 of 6 games have White's knight visit f3 at some point"
    );
    assert!(
        !text.contains("[White \"Botvinnik, Mikhail\"]"),
        "negative control: this game's White knight only ever goes to c3, never f3"
    );

    // Combination: the same FEN pattern AND Player "Fischer" in one
    // criteria file — both Fischer games satisfy the pattern.
    let mut combo = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "fen-wildcard-combo",
    );
    combo.filters.fen_pattern = Some(FenPatternFilter {
        pattern: knight_on_f3.to_string(),
        both_sides: false,
    });
    combo.filters.tag_rules = vec![tag_rule(TagName::Player, TagOp::Prefix, "Fischer")];
    run_succeeding(combo, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("fen-wildcard-combo.pgn")).unwrap(),
        2,
        "both Fischer games satisfy the FEN pattern"
    );
}

/// Textual opening-line ("variation") filters: positive on the game whose
/// opening matches the given move prefix, negative on a game with a
/// different opening, and combined with a Result tag rule.
#[tokio::test]
async fn textual_variation_matches_the_opening_prefix_and_combines_with_result() {
    let (engine, caps) = resolve_engine().await;
    let dest = tempfile::tempdir().unwrap();
    let jobs_root = tempfile::tempdir().unwrap();
    let eco_file = eco_file_path();

    let mut positive = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "variation-positive",
    );
    positive.filters.textual_variations = vec!["e4 e5 Nf3 Nc6".to_string()];
    run_succeeding(positive, &engine, &caps, jobs_root.path(), &eco_file).await;
    let text = read_to_string(&dest.path().join("variation-positive.pgn"));
    assert_eq!(
        count_games_in_file(&dest.path().join("variation-positive.pgn")).unwrap(),
        2,
        "the Tal-Botvinnik Ruy Lopez and the Fischer-Spassky Italian both open 1.e4 e5 2.Nf3 Nc6"
    );
    assert!(text.contains("[White \"Tal, Mikhail\"]"));
    assert!(
        !text.contains("[White \"Botvinnik, Mikhail\"]"),
        "negative control: this game opens 1.d4 d5, not 1.e4 e5"
    );

    // Negative control fixture-level: a disjoint opening line matches only
    // the one game that actually starts that way.
    let mut negative = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "variation-negative",
    );
    negative.filters.textual_variations = vec!["d4 d5".to_string()];
    run_succeeding(negative, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("variation-negative.pgn")).unwrap(),
        1
    );
    assert!(read_to_string(&dest.path().join("variation-negative.pgn"))
        .contains("[White \"Botvinnik, Mikhail\"]"));

    // Combination: the same opening-line filter AND a Result tag rule
    // (`-v` and `-t` are two different files/mechanisms) isolates one game.
    let mut combo = base_spec(
        vec![filters_fixture("players-results-dates.pgn")],
        dest.path().to_path_buf(),
        "variation-result-combo",
    );
    combo.filters.textual_variations = vec!["e4 e5 Nf3 Nc6".to_string()];
    combo.filters.tag_rules = vec![tag_rule(TagName::Result, TagOp::Prefix, "1-0")];
    run_succeeding(combo, &engine, &caps, jobs_root.path(), &eco_file).await;
    assert_eq!(
        count_games_in_file(&dest.path().join("variation-result-combo.pgn")).unwrap(),
        1,
        "of the two games matching the opening line, only Tal's has Result 1-0 (the Fischer \
         game is unfinished, Result \"*\")"
    );
    assert!(
        read_to_string(&dest.path().join("variation-result-combo.pgn"))
            .contains("[White \"Tal, Mikhail\"]")
    );
}
